ws-4020/mobile-app-crib-notes

santoku-app/src/app/components/parts/StatefulLoginForm.tsx

None
[AB#5148](https://dev.azure.com/ws-4020/d7a19fb0-b312-4b39-8b66-3fc0f61016f5/_workitems/edit/5148)

🐛: bugfix inputtext hides behind keyboard on iOS

---

santoku-app/ios/Podfile.lock
santoku-app/package.json

> npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
> npm ERR!
> npm ERR!
> npm ERR! Invalid: lock file's expo@39.0.4 does not satisfy expo@^38.0.9
> npm ERR!
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/ryotan/.npm/_logs/2020-11-20T02_42_47_821Z-debug.log
→ Remove old `expo` from `devDependencies`.
> Analyzing dependencies
> [!] CocoaPods could not find compatible versions for pod "Folly":
>   In snapshot (Podfile.lock):
>     Folly (from `../node_modules/react-native/third-party-podspecs/Folly.podspec`)
> 
>   In Podfile:
>     Folly (from `../node_modules/react-native/third-party-podspecs/Folly.podspec`)
> 
> It …

🐛: Remove expo from devDependencies, upgrade Podfile.lock

---

santoku-app/src/app/components/pages/auth/StatelessAuth.tsx

- Androidの場合KeyStoreには鍵を保存していて実際のデーターはSharedPreferenceに保管する旨を記載
None
- アプリを起動して、サイドメニューを表示する
- ステートレスな認証の画面を表示する
[AB#5166](https://dev.azure.com/ws-4020/d7a19fb0-b312-4b39-8b66-3fc0f61016f5/_workitems/edit/5166)

🐛:  KeyStoreとKeychainに関する説明を修正

---

santoku-app/src/app/components/basics/TextButton.tsx
santoku-app/src/app/components/parts/StatefulLoginForm.tsx

- 汎用的はTextButtonを作ること(NativeBaseのButtonのpropsのtypeがすぐにわからなかった)
- アプリを起動して、サイドメニューを表示する
- サイドメニューで「Webアプリとの認証情報の連携」が表示される
- Webアプリとの認証情報の連携画面を表示してタイトルが「Webアプリとの認証情報の連携」になっている「
- Webアプリとの認証情報の連携画面のログインボタンが、入力項目と同じ幅になっている、入力チェックエラーの状況におうじてDisableのスタイルが切り替わる
[AB#5164](https://dev.azure.com/ws-4020/d7a19fb0-b312-4b39-8b66-3fc0f61016f5/_workitems/edit/5164)

🐛: ログインボタンにTextButtonを使うように変更

---

santoku-app/src/app/hooks/validation/useValidation.ts

🐛: 入力チェックのタイミングはonChangeTextやonBlurから切り離した

---

.github/renovate.json5
README.md
nginx/default.conf.template
package-lock.json
package.json

- 末尾スラッシュなしでアクセスすると、80番ポートにリダイレクトされてしまう
- `http://localhost:3001/mobile-app-crib-notes/reference` が `http://localhost/mobile-app-crib-notes/reference/` に
- Nginxのレスポンスの`Location`は、Dockerでマッピングしたポートではなく、Nginxがlistenしているポートを指すため（あるある）
- NginxがlistenするポートとDockerでマッピングするポートを合わせることで回避
---
たまにHTMLで確認しておいたほうがいいことがあるので、追加しました。

🔨: Serve built html files from nginx

---

santoku-app/ios/GoogleService-Info.dummy.plist

🐛: FCMのダミーの設定ファイルだと起動していなかったので修正

---

santoku-app/android/app/build.gradle

- android のリリース用IDについている `.release` suffixが不要（不自然）なため除去
---
なし

android のリリース用IDについている.release suffixを除去

---

santoku-app/src/app/components/parts/notification/DeviseTokenNotificationForm.tsx
santoku-app/src/app/components/parts/notification/TopicNotificationForm.tsx

- API呼び出し後の結果通知（onSendやonSentErrorなど）
- エラーハンドリング
---
なし

🐛: 不要な判定を削除してアプリが処理できない場合はユーザーに通知する

---

.github/renovate.json5

---
`SantokuApp/ios`と`SantokuApp/android`をディレクトリごと除外するべきか悩みましたが、いったんGradleのみ外してみようと思います。

🔧: Fix Renovate configuration files

---

.github/renovate.json5
SantokuApp/package.json
SantokuApp/src/App.tsx

🌱: Use `expo-keep-awake` while running in development mode

---

SantokuApp/android/gradle.properties
SantokuApp/ios/Podfile
SantokuApp/ios/Podfile.lock

⬆: Update Flipper to 0.84.0

---

.github/workflows/app.yaml
.github/workflows/gh-pages.yaml

---
GitHub Actionsのトリガーとして`pull_request_target`を利用していましたが、使い方が間違えていたようなのでいったんリバートします。
`triage.yaml`は、`pull_request_target`が適切だと思うのでそのままにしています。
参考: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
This reverts commit 3110f7b7

⏪️: pull request target から pull request に変更

---

SantokuApp/.script/jobs/reset-cache-macos.js
SantokuApp/README.md

- `reset-cache:all`を実行しても`pod update`は実行されないようにしました
---
CocoaPodsをHomebrewでもインストールしている環境でテストできていないので、確認をお願いしたいです。

🔨: Fix reset-cache script to use bundle exec

---

docs/reference/notification/client.md
docusaurus.config.js

💄: Enable code block syntax highlighting of Ruby and Groovy

---

.github/renovate.json5
SantokuApp/package-lock.json
SantokuApp/package.json
SantokuApp/patches/expo-constants+9.3.5.patch
SantokuApp/patches/expo-updates+0.4.2.patch

---
- `SantokuApp/android`ディレクトリで`npm run reset-cache:all && ./gradlew bundleDebug && ./gradlew assembleDebug && npm run android`を実行して、正常に完了することを確認。
以下の箇所で`execute`の引数に空配列を渡しているので、環境変数が引き継がれなくなっています。そのため、asdf-vmでインストールしたNode.jsが正しく動きません。
* https://github.com/expo/expo/blob/sdk-40/packages/expo-constants/scripts/get-app-config-android.gradle#L13
* https://github.com/expo/expo/blob/sdk-40/packages/expo-updates/scripts/create-manifest-android.gradle#L13

🔨: Add patch-package to run Gradle tasks in asdf-vm env

---

SantokuApp/android/gradle.properties
SantokuApp/ios/Podfile
SantokuApp/ios/Podfile.lock

---
Xcode 12.5に上げるとFlipperでビルドエラーになったので更新。`Flipper-Folly`のバージョンが2.5.3になればエラーは解消するみたいだけど、Flipper自体も更新されているのでまとめてあげてます。

⬆: Update Flipper to 0.87.0

---

package-lock.json

- #213 Lock file maintenance でfseventsのdependenciesからnanが消えたためエラーが発生
---
`package-lock.json`を削除してから`npm i`を実行したら`nan`が依存に含まれるようになりました。
GitHub ActionsではLinux上で`npm ci`が実行されていましたが、`fsevents`はLinux上ではインストールされないので検知されませんでした。
https://github.com/ws-4020/mobile-app-crib-notes/runs/2483061264#step:6:11
> Skipping 'fsevents' build as platform linux is not supported

🐛: Fix an error occurred when installing fsevents on macOS

---

.github/renovate.json5

---
これでDocusaurusを2.0.0-alpha.75に更新するPRが作成されれば成功ですが、テストの仕方がわからない。。。

🐛: Fix renovate packageRules of Docusaurus

---

docs/distribution/usecase/index.mdx
docs/docusaurus/index.mdx
docs/react-native/learn/advance/react-navigation-param.mdx
docs/react-native/learn/basic-concepts.mdx
docs/react-native/learn/basic-concepts/react-native-basics/components.mdx
docs/react-native/learn/basic-concepts/react-native-basics/components/button.mdx
docs/react-native/learn/basic-concepts/react-native-basics/components/image.mdx
docs/react-native/learn/basic-concepts/react-native-basics/components/lists.mdx
docs/react-native/learn/basic-concepts/react-native-basics/components/lists/flat-list.mdx
docs/react-native/learn/basic-concepts/react-native-basics/components/lists/section-list.mdx
docs/react-native/learn/basic-concepts/react-native-basics/components/scroll-view.mdx
docs/react-native/learn/basic-concepts/react-native-basics/components/text.mdx
docs/react-native/learn/basic-concepts/react-native-basics/components/touchable-opacity.mdx
docs/react-native/learn/basic-concepts/react-native-basics/components/view.mdx
docs/react-native/learn/basic-concepts/react-native-basics/design.mdx
docs/react-native/learn/basic-concepts/react-native-basics/design/flexbox.mdx
docs/react-native/learn/basic-concepts/react-native-basics/design/height-and-width.mdx
docs/react-native/learn/basic-concepts/react-native-basics/design/style.mdx
docs/react-native/learn/basic-concepts/react-navigation-basics.mdx
docs/react-native/learn/basic-concepts/react-navigation-basics/modal.mdx
docs/react-native/learn/basic-concepts/react-navigation-basics/stack.mdx
docs/react-native/learn/basic-concepts/react-navigation-basics/tab.mdx
docs/react-native/learn/getting-started.mdx
docs/react-native/learn/getting-started/launch-created-app.mdx
docs/react-native/learn/getting-started/setting-up-development-environment.mdx
docs/react-native/santoku/development/build-variants.mdx
docs/react-native/troubleshooting/unable-to-load-script.mdx

---
#159 で`textlint-rule-preset-ja-technical-writing`が6系に更新された際に、[カンマは1文中に3つまで](https://github.com/textlint-ja/textlint-rule-preset-ja-technical-writing#%E3%82%AB%E3%83%B3%E3%83%9E%E3%81%AF1%E6%96%87%E4%B8%AD%E3%81%AB3%E3%81%A4%E3%81%BE%E3%81%A7)のルールで一文ずつに分割する規則が変更されたためLintエラーになったようです。
以前 #159 のブランチで修正していたのですが、RenovateにPRを再作成してもらった後の再反映が漏れていました🙇‍♂️ 
#159 の差分には含まれない箇所でのエラーだったのでGitHub Actionsでは検知できませんでした。
#159 のGitHub Actions: https://github.com/ws-4020/mobile-app-crib-notes/runs/2551083985
検知したGitHub Actions（master）: https://github.com/ws-4020/mobile-app-crib-notes/runs/2551641061

💄: Fix lint errors (ja-technical-writing/max-comma)

---

docs/react-native/learn/todo-app/screens/stack.mdx

🖋: StackナビゲーションページでToDo一覧画面のヘッダーにログインボタンが表示されていたので表示しないように修正

---

docs/react-native/learn/todo-app/networking/api-request.mdx
docs/react-native/learn/todo-app/networking/generate-api-client.mdx

🐛: REST API呼びだしの中で表記が間違っているものなどを修正

---

docs/react-native/learn/todo-app/screens/auth.mdx

---
[ドキュメント](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/todo-app/screens/stack#%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E3%83%9C%E3%82%BF%E3%83%B3%E3%81%AE%E8%BF%BD%E5%8A%A0)で追加している`headerRight`も一緒に消すべきでした
https://github.com/ws-4020/mobile-app-crib-notes/pull/303

📝: 別件の対応時に追加した行を消すDiffがもれているので対応

---

docs/react-native/learn/basic-concepts/react-navigation-basics/stack.mdx

- StackNavigationPropに何かしらジェネリクスを指定する必要があるが、今回はパラメータ定義は不要であるため、ベースとなるParamListBaseを指定。（anyを指定するよりは良いと判断）
---
なし

♻️: VSCode上でコンパイルエラーになるソースを修正

---

docusaurus.config.js

---
なんとなく、統一感がなくなってるなぁ、と思ったので提案です。分かりにくくなりそうとかだったら取り下げます。

💄: ナビゲーションバーのラベルを英語に統一

---

docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
docs/react-native/learn/todo-app/networking/api-request.mdx
docs/react-native/learn/todo-app/screens/exercise.mdx
docs/sidebars.js

---
- 演習課題自体のmdであるexercise.mdx以外にヒットなし
- docs\react-native\learn\todo-app\networking\api-request.mdxに演習課題でToDoの削除を実装している場合の文言があったため削除
なし

🖋: 演習課題をREST APIとの接続の後ろに移動

---

santoku-app/android/app/google-services.dummy.json

🐛: santoku-appのgoogle-services.dummy.jsonをそのまま使えるように修正

---

.github/renovate.json5

---
Globを使わないと、直下のやつだけ無視されてしまうらしい。

🔨: react-native-samplesの中はRenovateの対象外にする

---

website/docs/react-native/santoku/decisions.mdx
website/docs/react-native/santoku/decisions/adr-001-error-handling.mdx

---
方式設計に合わせて、「エラーハンドリング」に変更しました

✨: ADRのタイトルを「エラーのハンドリング方法」から「エラーハンドリング」に変更

---

example-app/SantokuApp/android/app/src/main/AndroidManifest.xml

- Androidで分割表示したときに、アクティビティが再起動されなくなりました
---
参考にしたドキュメント
- [マルチウィンドウのサポート - Android デベロッパー](https://developer.android.com/guide/topics/ui/multi-window)
- [構成の変更を処理する - Android デベロッパー](https://developer.android.com/guide/topics/resources/runtime-changes)
- [\<activity\> - Android デベロッパー](https://developer.android.com/guide/topics/manifest/activity-element#config)

🐛: Androidでウィンドウを分割してリサイズすると、Home画面に戻ってしまう問題に対応

---

example-app/SantokuApp/ios/SantokuApp.xcodeproj/project.pbxproj

✨: Releaseモードのシミュレータ起動ではCPUアーキテクチャからarm64を除外するように変更

---

example-app/SantokuApp/ios/SantokuApp/Debug.plist
website/docs/react-native/santoku/development/build-configuration/build-type-configurations.mdx

- Debug/DebugAdvancedでビルドして開発しているときも、`localhost`以外のホストにはHTTPS接続が必須になります。
---
[App Transport Security - ビルドタイプ](https://ws-4020.github.io/mobile-app-crib-notes/react-native/santoku/development/build-configuration/build-type-configurations#app-transport-security)で、「有効（`localhost`を除外）」と設計していたのですが、そのとおりに実装されていなかったので修正しました。

🩹: Debugの場合にATSが完全に無効になっていたのを、localhostのみ無効にするように修正

---

.github/renovate.json5

- #427 と #428 で個々に更新しようとしてエラーが発生しているので、まとめて更新するように

✨: React Native Firebase関連のパッケージをまとめて更新する設定に変更

---

.github/renovate.json5

- （もともと@types/react-test-rendererが対象外とされていたので修正）

✨: react-test-rendererをRenovate対象外にする

---

example-app/SantokuApp/android/app/build.gradle

---
以下のドキュメントに従って設定しました。
[難読化されたビルド バリアントを保持する - Firebase Crashlytics](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?hl=ja&platform=android#keep_obfuscated_build_variants)

🔨: Debugの時は、Androidの難読化ファイルをCrashlyticsにアップロードしないようにする

---

example-app/SantokuApp/src/App.tsx
example-app/SantokuApp/src/framework/index.ts
example-app/SantokuApp/src/framework/message/BundledMessageLoader.ts
example-app/SantokuApp/src/framework/message/Message.test.ts
example-app/SantokuApp/src/framework/message/Message.ts
example-app/SantokuApp/src/framework/message/index.ts
example-app/SantokuApp/src/generated/BundledMessages.ts
example-app/SantokuApp/src/navigation/DemoStackNav.tsx
example-app/SantokuApp/src/screens/demo/DemoScreen.tsx
example-app/SantokuApp/src/screens/demo/index.ts
example-app/SantokuApp/src/screens/demo/message/MessageListItem.tsx
example-app/SantokuApp/src/screens/demo/message/MessageScreen.tsx
example-app/SantokuApp/src/screens/demo/message/MessageTemplate.tsx
example-app/SantokuApp/src/screens/demo/message/index.ts
example-app/SantokuApp/src/screens/demo/message/useMessage.tsx

🌱: メッセージ管理の部品を追加

---

example-app/SantokuApp/ios/Podfile.lock
example-app/SantokuApp/package-lock.json

---
- `eslint-plugin-import` etc. が `node_modules` 直下ではなく `eslint-config-universe` のみのdependencyとして解決されるようになったのが直接原因
- なぜこのように解決されるようになったのかの解析は時間がかかりそうだったので、いったん暫定対応としてRevert

⏪: ESLintの実行失敗の暫定対応

---

.azure-pipelines/deploy.yaml
.github/workflows/app.yaml
.github/workflows/delete-deploygate-distribution-pages.yaml
.github/workflows/gh-pages-deploy.yaml
.github/workflows/gh-pages.yaml
.idea/dictionaries/shared.xml
.tool-versions
example-app/SantokuApp/package-lock.json
website/package-lock.json

---
- asdfでのコマンド実行に失敗する場合、各プラグインで対象バージョンがインストールされていることを確認してください。
- asdfを使っている場合、Rubyの更新に伴って`bundle install`や`npm run pod-install`に失敗する場合があります。`.bundle/vendor`ディレクトリを削除して、再度 `bundle install`を実行してください。

⬆: Bump tool versions

---

.github/renovate.json5

📌: expo-randomをrenovateの管理対象から除外

---

website/docs/react-native/santoku/development/implement/logs-implementation.mdx

https://github.com/ws-4020/mobile-app-crib-notes/discussions/570 の対応

✨: ログ出力の開発ガイドで、表現の微修正、Windows環境を考慮したコマンドの記載に対応

---

website/docs/react-native/santoku/development/implement/app-launch-with-build-variants.mdx

---
https://github.com/ws-4020/mobile-app-crib-notes/discussions/571 の対応です。

📝: 環境切り替えの開発ガイドで読みづらかった部分を修正

---

example-app/SantokuApp/src/framework/message/Message.test.ts
example-app/SantokuApp/src/framework/message/Message.ts

---
https://github.com/ws-4020/mobile-app-crib-notes/discussions/573 の対応

✨: メッセージ取得時に、同じプレースホルダが複数存在した場合は、全て置換するように変更

---

example-app/SantokuApp/.gitignore
example-app/SantokuApp/package.json

🔨: テスト用のスクリプト追加

---

website/src/pages/trademark.md

✏️: Google Playの商標を追記

---

example-app/SantokuApp/src/screens/account/TermsOfServiceAgreementScreen.tsx
example-app/SantokuApp/src/screens/home/HomeScreen.tsx
example-app/SantokuApp/src/screens/team/TeamDetailScreen.tsx

- デモ画面のヘッダタイトルは固定文字列のまま変更無し。
---
なし

🎨: 各画面のヘッダタイトルをMessageLoaderから取得するように変更

---

website/docs/react-native/santoku/requirements/non-functional/usability.mdx

🩹: Fix Apple OS names

---

.github/renovate.json5

🔨: Update Renovate settings to disable unnecessary update requests

---

example-app/SantokuApp/ios/Podfile.lock
example-app/SantokuApp/src/framework/authentication/AuthenticationService.test.ts
example-app/SantokuApp/src/framework/authentication/AuthenticationService.ts

---
サインアップしてもsantoku-app-backendからセッションが払い出されてるわけではない（ログインしてない）のでアクティブアカウントIDをセキュアストレージに保存しないように変更しました

🐛: サインアップ後はアクティブアカウントIDをセキュアストレージに保存しないように修正

---

.azure-pipelines/deploy.yaml

---
↓を参考にしました。
https://docs.microsoft.com/ja-jp/azure/devops/pipelines/ecosystems/ruby?view=azure-devops#use-a-specific-ruby-version

🚑: azure pipelineで使用しているRubyのバージョンを3.0.xを使用するように変更

---

example-app/SantokuApp/src/navigation/RootStackNav.tsx
example-app/SantokuApp/src/screens/team/TeamDetailScreen.tsx

---
新しい方式の検証とかで、リリースモードでもデモ画面を使用したいため、このPRを上げました。

🚩: リリースモードでもデモ画面を表示できるように変更

---

example-app/SantokuApp/src/framework/authentication/AuthenticationService.test.ts
example-app/SantokuApp/src/framework/authentication/AuthenticationService.ts
example-app/SantokuApp/src/framework/authentication/index.ts
example-app/SantokuApp/src/framework/index.ts
example-app/SantokuApp/src/screens/demo/authentication/AuthenticationScreen.tsx
example-app/SantokuApp/src/screens/demo/authentication/useAuthentication.tsx

♻️: 認証部品のリファクタ

---

example-app/SantokuApp/src/framework/authentication/SecureStorageAdapter.test.ts
example-app/SantokuApp/src/framework/authentication/SecureStorageAdapter.ts

---
変更した理由は以下を参照ください。
https://github.com/ws-4020/mobile-app-crib-notes/pull/640#issuecomment-984500781

✨: セキュアストレージに保存する際のオプションをWHEN_UNLOCKEDに変更

---

example-app/SantokuApp/ios/SantokuApp/AppDelegate.m

---
【関連issue】
https://github.com/facebook/react-native/issues/16376
【参考ドキュメント】
https://amanhimself.dev/blog/rctbridge-required-dispatch-sync-to-load-warning/

🩹: iOSでアプリ起動時に警告メッセージが表示される事象の対応

---

example-app/SantokuApp/ios/Podfile.lock
example-app/SantokuApp/patches/README.md
example-app/SantokuApp/patches/react-native+0.64.3.patch

---
最低限、`npm ci`してから`npm run pod-install`して、`Podfile.lock`にdiffがでなくなることを確認してもらいたいです。

🩹: Use relative paths for pod spec to keep checksum stable

---

website/src/pages/trademark.md

Apple：「Appleのロゴ」「watchOS」「tvOS」「Instruments」「Objective-C」「Swift」
Google：「Pixel」「Androidロボット」
~~Kotlin Foundation：「Kotlin」~~
PostgreSQL Community Association of Canada：「Postgres」「PostgreSQL」「Slonikロゴ」
Motorola Trademark Holdings, LLC：「moto」
ソニー株式会社：「Xperia」
Samsung Electronics Co., Ltd.：「Galaxy」
ASUSTeK Computer Inc.：「ZenFone」
株式会社デンソーウェーブ：「QRコード」
---
Kotlinはガイドライン上記載を必須とする旨が見当たらなかったので「その他、本サイトに〜」に包括する。
端末商品名はガイドラインそのものが見当たらなかったが商品名ということで記載した方が良いと考えられるので記載する。
Azureロゴはガイドライン上記載を必須とする旨が見当たらなかったので「その他、本サイトに〜」に包括する。
Firebaseロゴはガイドライン上記載を必須とする旨が見当たらなかったので「その他、本サイトに〜」に包括する。

✏️: 表記が必要な商標を追加

---

example-app/SantokuApp/src/components/snackbar/Snackbar.test.tsx
example-app/SantokuApp/src/components/snackbar/Snackbar.tsx
example-app/SantokuApp/src/components/snackbar/__snapshots__/Snackbar.test.tsx.snap

🚑: スナックバーがアンマウントされない事象の対応

---

website/docs/react-native/learn/todo-app/screens/todo-board.mdx

🚑: 学習コンテンツのToDo一覧画面のhtmlリンク切れ対応

---

example-app/SantokuApp/src/App.test.tsx
example-app/SantokuApp/src/navigation/RootStackNav.tsx

- 他の画面への遷移（最終的にはやった方が便利）
---
最終的には遷移先の画面を選択できるようにしたい

🧑‍💻: デバッグメニューからデモ画面へ遷移

---

website/docs/react-native/santoku/design/context/theme.mdx
website/docs/react-native/santoku/design/screen-specs/basic-policy.mdx
website/docs/react-native/santoku/design/screen-specs/common-parts/button/overview.mdx

💄: React Native Elementsのドキュメントへのリンク切れを修正

---

example-app/SantokuApp/src/navigation/RootStackNav.tsx

🚑️: DEVビルドの場合のみ開発メニューにデモへのリンクを追加。

---

website/docs/react-native/learn/getting-started/setting-up-development-environment.mdx

🩹: Fix environmental variables of Android SDK

---

website/.htmltest.yaml

💚: htmltestのタイムアウト対応

---

example-app/SantokuApp/src/navigation/DemoStackNav.tsx
example-app/SantokuApp/src/navigation/types.ts
example-app/SantokuApp/src/screens/demo/DemoScreen.tsx
example-app/SantokuApp/src/screens/demo/cache/CacheScreen.tsx
example-app/SantokuApp/src/screens/demo/cache/FileInfo.tsx
example-app/SantokuApp/src/screens/demo/cache/index.ts
example-app/SantokuApp/src/screens/demo/cache/useCacheDirectory.ts
example-app/SantokuApp/src/screens/demo/index.ts

✨: キャッシュディレクトリ内のファイルの表示と一括削除が行えるデモ画面の追加

---

example-app/SantokuApp/src/generated/api/api.ts
example-app/SantokuApp/src/screens/demo/push-notification/usePushNotification.tsx
example-app/api-document/openapi.yaml
example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/presentation/restapi/account/MyAccountDeviceTokenAction.java

- クライアント側での登録トークン定期更新処理の実装
- 現時点ではデモ画面から手動で登録トークンの登録・削除を行う機能のみ
---
なし

👔: 定期更新時も同じFCM登録トークンを利用できるようにAPI仕様を変更

---

website/src/pages/trademark.md

📝: 商標についてのページにiPadOSを追加

---

example-app/SantokuApp/src/components/reactQuery/useDefaultGlobalErrorHandler.ts
example-app/SantokuApp/src/framework/error/ApplicationError.ts
example-app/SantokuApp/src/framework/error/RequestTimeoutError.ts
example-app/SantokuApp/src/screens/demo/authentication/useAuthentication.tsx

- グローバルエラーハンドリングで処理してもcatch句は呼ばれるので、画面側をシンプルにするために変更しました
---
なし

✨: ApplicationErrorはグローバルエラーハンドリングしないよう修正

---

example-app/SantokuApp/.eslintrc.js

#808 で`plugin:react-hooks/recommended`を`.eslintrc`の`extends`から外したが（`universe/native`に入っていると思ったため）、`eslint-config-universe`では、[`react-hooks/exhaustive-deps`を`off`に設定](https://github.com/expo/expo/blob/master/packages/eslint-config-universe/shared/react.js#L40)していたため、`plugin:react-hooks/recommended`を`.eslintrc`の`extends`に再度追加しました。
---
なし

🚑: .eslintrc.jsにreact-hooks/recommendedを追加

---

example-app/SantokuApp/src/components/overlay/snackbar/Snackbar.test.tsx
example-app/SantokuApp/src/components/overlay/snackbar/Snackbar.tsx
example-app/SantokuApp/src/components/overlay/snackbar/WithSnackbar.tsx

🐛: Snackbarが意図せず再表示されてしまう事象の対応

---

example-app/SantokuApp/jest.config.js
example-app/SantokuApp/jest/setup/react-query.js

🔧: In Jest testing, suppress warning log by React Query

---

website/src/css/custom.css

---
| Before | After |
|--------|------|
| ![Aspect ratio is broken...](https://user-images.githubusercontent.com/44867563/162423152-266c73c3-0f80-4e1f-9c15-7930ff4f644b.png) | ![スクリーンショット 2022-04-08 20 00 44](https://user-images.githubusercontent.com/44867563/162423221-7eae1ea5-cbfd-4d22-bb0d-34365088546c.png) |
なし

🚑: Fix broken aspect ratio of images in Tab

---

website/docs/react-native/santoku/development/build-configuration/build-variants.mdx

🚑: Fix wrong option name to run Android variant

---

example-app/SantokuApp/ios/SantokuApp/Info.plist

🚑: Align the version of the iOS Release build with the others

---

.tool-versions

＜参考＞
https://reactnative.dev/docs/environment-setup（React Nativeの公式では`Azul Zulu`をお薦めしている）
https://github.com/halcyon/asdf-java/blob/master/data/jdk-macosx-aarch64.tsv#L239
なし
---
なし

🔧: asdfで使用するJavaのディストリビューションをAzul Zuluに変更

---

example-app/SantokuApp/src/components/picker/SelectPicker.tsx
example-app/SantokuApp/src/components/picker/useSelectPickerAndroidUseCase.ts
example-app/SantokuApp/src/components/picker/useSelectPickerUseCase.ts
example-app/SantokuApp/src/screens/demo/picker/usePickerScreenUseCase.ts

🔧:onSelectedItemChangeのパラメータ定義を変更

---

.github/renovate.json5

📌: @react-native-async-storageをRenovate管理から除外

---

example-app/SantokuApp/ios/SantokuApp.xcodeproj/project.pbxproj
example-app/SantokuApp/ios/SantokuApp/en.lproj/InfoPlist.strings
example-app/SantokuApp/ios/SantokuApp/ja.lproj/InfoPlist.strings

✨: iOS Nativeのローカライズ対応

---

.github/renovate.json5
website/package-lock.json
website/package.json

- `file-loader`
- `@svgr/webpack`
- `url-loader`
- `prism-react-renderer`
---
今回の対応で、`npx create-docusaurus@latest my-website classic --typescript`で初期PJを作成した時の`dependencies`と同じライブラリが、`dependencies`に設定されてます。
（`redocusaurus`など個別に入れているものは除く）

🩹: websiteのpackage.jsonのdependenciesを見直し

---

.github/renovate.json5

📌: gradle-download-taskをRenovate管理から除外

---

website/docs/react-native/learn/todo-app/networking/generate-api-client.mdx
website/docs/react-native/learn/todo-app/screens/auth.mdx

- `App.tsx`に、`GestureHandlerRootView`を追加
- `package.json`のscripts追加に伴う対応
＜参考＞
- [⬆️: Upgrade Expo SDK to 45 ](https://github.com/ws-4020/rn-spoiler/pull/109)
- [⬆️: Upgrade Expo SDK to 44 ](https://github.com/ws-4020/rn-spoiler/pull/106)
---
なし

📝: 学習コンテンツにrn-spoilerのExpo SDK 44、45対応を反映

---

example-app/SantokuApp/jest/setup/react-native-reanimated.js
example-app/SantokuApp/src/components/picker/DateTimePicker.ios.test.tsx
example-app/SantokuApp/src/components/picker/DateTimePicker.ios.tsx
example-app/SantokuApp/src/components/picker/PickerBackdrop.test.tsx
example-app/SantokuApp/src/components/picker/PickerBackdrop.tsx
example-app/SantokuApp/src/components/picker/PickerContainer.test.tsx
example-app/SantokuApp/src/components/picker/PickerContainer.tsx
example-app/SantokuApp/src/components/picker/SelectPicker.test.tsx
example-app/SantokuApp/src/components/picker/SelectPicker.tsx
example-app/SantokuApp/src/components/picker/SelectPickerItem.tsx
example-app/SantokuApp/src/components/picker/SelectPickerItems.android.test.tsx
example-app/SantokuApp/src/components/picker/SelectPickerItems.android.tsx
example-app/SantokuApp/src/components/picker/YearMonthPicker.test.tsx
example-app/SantokuApp/src/components/picker/YearMonthPicker.tsx
example-app/SantokuApp/src/components/picker/__snapshots__/DateTimePicker.ios.test.tsx.snap
example-app/SantokuApp/src/components/picker/__snapshots__/PickerBackdrop.test.tsx.snap
example-app/SantokuApp/src/components/picker/__snapshots__/PickerContainer.test.tsx.snap
example-app/SantokuApp/src/components/picker/__snapshots__/SelectPicker.test.tsx.snap
example-app/SantokuApp/src/components/picker/__snapshots__/SelectPickerItems.android.test.tsx.snap
example-app/SantokuApp/src/components/picker/__snapshots__/YearMonthPicker.test.tsx.snap
example-app/SantokuApp/src/components/picker/useDateTimePickerIOSUseCase.ts
example-app/SantokuApp/src/components/picker/usePickerBackdropUseCase.ts
example-app/SantokuApp/src/components/picker/usePickerContainerUseCase.ts
example-app/SantokuApp/src/components/picker/useSelectPickerUseCase.ts
example-app/SantokuApp/src/components/picker/useYearMonthPickerUseCase.ts
example-app/SantokuApp/src/framework/utilities/useVisibility.ts

以下のReact Native Animatedのissueに記載されている通り、Layout Animationsを使用した場合に、ページコンテンツがナビゲーションヘッダに隠れてしまう事象が発生しました。
[React Navigation (Native-stack) header hide screen after reanimated layout animation run [only in Android] ](https://github.com/software-mansion/react-native-reanimated/issues/2906)
本PRはその対応になります。
---
なし

🐛: PickerコンポーネントでReanimatedのLayout Animationsを使用しないように変更

---

.github/renovate.json5

📌: @react-native-community/datetimepickerをRenovate管理から除外

---

example-app/SantokuApp/patches/README.md
example-app/SantokuApp/patches/react-native-reanimated+2.8.0.patch
example-app/SantokuApp/src/components/picker/DateTimePicker.ios.tsx
example-app/SantokuApp/src/components/picker/usePickerContainerUseCase.ts

- related issue/pr
- https://github.com/software-mansion/react-native-reanimated/issues/3296
- https://github.com/software-mansion/react-native-reanimated/pull/3302
---
none

🐛: [iOS] Fixed an issue where animations were not executed in the Picker component.

---

example-app/SantokuApp/src/@types/react-navigation.d.ts
example-app/SantokuApp/src/__snapshots__/App.test.tsx.snap
example-app/SantokuApp/src/navigation/HomeStackNav.tsx
example-app/SantokuApp/src/navigation/TeamStackNav.tsx
example-app/SantokuApp/src/screens/home/HomeScreen.tsx
example-app/SantokuApp/src/screens/team/TeamDetailScreen.tsx

- https://github.com/react-navigation/react-navigation/issues/10175
- https://github.com/software-mansion/react-native-screens/issues/1276
- https://github.com/software-mansion/react-native-screens/issues/1251
---
なし

💄: Changed to use stack instead of native stack in bottom tab

---

.github/renovate.json5

📌: Exclude react-native-svg from renovate management

---

example-app/SantokuApp/package-lock.json
example-app/SantokuApp/package.json

- Features added in v11 in @testing-library/react-native will no longer be available.(No part of Santoku currently uses v11 features)
The v11 of @testing-library/react-native requires jest 28 or higher, but Santoku (Expo) depends on jest 26.x.
Therefore, downgrade @testing-library/react-native to v10.
---
none

⬇️: Downgrade @testing-library/react-native to v10

---

example-app/SantokuApp/jest/__mocks__/@react-native-firebase/messaging.ts

- Mock `setDeliberatelyMetricsExportToBigQuery` added to `@react-native-firebase/messaging`
none

🚨: Fix react-native-firebase-messaging mock

---

example-app/SantokuApp/src/bases/core/errors/ApplicationError.ts
example-app/SantokuApp/src/bases/core/errors/RuntimeError.test.ts
example-app/SantokuApp/src/bases/core/errors/RuntimeError.ts

🐛: Fix a bug that errorCode of Runtime(Application)Error is not set.

---

.github/renovate.json5

---
- close #1033
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1024
- https://github.com/ws-4020/mobile-app-crib-notes/pull/996
- https://github.com/ws-4020/mobile-app-crib-notes/commit/f88238faf75a7d54d4896c18a9420bd21d51ff4d `Add proguard settings`
none

📌: Exclude expo-build-properties from renovate management

---

.github/renovate.json5

- `com.google.firebase:firebase-crashlytics-gradle`
- `com.google.gms:google-services`
---
- close #1017
none

📌: Exclude dependencies used in firebase from renovate management

---

.github/renovate.json5
example-app/SantokuApp/package-lock.json
example-app/SantokuApp/package.json

- `fs-extra` 依存を明示 (devDependencies)
- `@types/fs-extra` version を `fs-extra` version に揃える
- renovate では `fs-extra` を型定義と一緒に更新するようにグループ化
- fs-extra の バージョンアップ
---
`./example-app/SantokuApp` にて 
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1039#discussion_r1119524377
close https://github.com/ws-4020/mobile-app-crib-notes/pull/1039

🧑‍💻: [SantokuApp] fs-extra ライブラリの型定義改善

---

.github/workflows/app.yaml
.github/workflows/gh-pages.yaml

lint が fail してても変更範囲外の場合人間がログを見ないとfailしていることに気づけ無いため
---
- 公式ドキュメント [reviewdog/reviewdog: 🐶 Automated code review tool integrated with any code analysis tools regardless of programming language](https://github.com/reviewdog/reviewdog#filter-mode)
> Filter mode
- 変更範囲外でfailしている例: https://github.com/ws-4020/mobile-app-crib-notes/pull/1041#discussion_r1119592303
- GitHub Actions ログ: https://github.com/ws-4020/mobile-app-crib-notes/actions/runs/4280671481/jobs/7452735912
- https://github.com/ws-4020/mobile-app-crib-notes/runs/11618956553
- > Filtered Findings (2)

🧑‍💻: [reviewdog] 変更範囲外で lint が fail した場合に PRのchecksをfailさせる

---

example-app/SantokuApp/jest/__mocks__/expo-constants.ts
example-app/SantokuApp/src/bases/core/configs/AppConfig.ts
website/docs/react-native/santoku/development/build-configuration/app-constants.mdx

Corrected a bug that caused the manifest to be undefined when OTA updating.
The Expo document states the following.
Use Constants.expoConfig instead of Constants.manifest, which behaves more consistently across EAS Build and Update.
Constants.expoConfig object defined in app.json and app.config.js files. For both classic and modern manifests, whether they are embedded or remote.
see: https://docs.expo.dev/versions/v48.0.0/sdk/constants/#nativeconstants
※ Expo46 documentation does not include a detailed description, so 48 one is used.
---
- /azp …

♻️: Use Constants.expoConfig instead of Constants.manifest.

---

example-app/SantokuApp/package-lock.json
example-app/SantokuApp/package.json

fs-extraのversion指定と^/~ は揃えておかないと Lock file maintenance by renovate でずれる可能性があった
---
```
$ git grep 'fs-extra"' package.json
package.json:    "@types/fs-extra": "^8.1.2",
package.json:    "fs-extra": "^8.1.0",
```
- きっかけ: https://github.com/ws-4020/mobile-app-crib-notes/pull/1043#discussion_r1119765874
- 後続のPR: https://github.com/ws-4020/mobile-app-crib-notes/pull/1045
- このPR (1048) が merge された後に 1045 を rebase 推奨

🐛: @types/fs-extra の version 指定ミス修正

---

website/docs/react-native/santoku/design/screen-specs/common-parts/webview/overview.mdx

📝: WebViewドキュメントの誤記を修正(onceScrollEnd -> onScrollEndOnce)

---

website/docs/react-native/santoku/development/dependency-management.md

📝: 型定義ファイルのバージョン指定に関する説明誤りを修正

---

example-app/SantokuApp/src/features/qa-question/components/CommentCard.tsx

| 修正前 (Pixel 6/Android 13) | 修正後 (Pixel 6/Android 13) |
| <img src="https://user-images.githubusercontent.com/38860388/223914562-f1a35e9f-bf8a-4cb3-952f-ea2ac1122335.png" width="50%" /> | <img src="https://user-images.githubusercontent.com/38860388/223914585-26ecd4c9-d361-4729-a02a-00a7364dcf47.png" width="50%" /> |
| 修正前 (Pixel 6/Android 13) | 修正後 (Pixel 6/Android 13) |
| <img src="https://user-images.githubusercontent.com/38860388/223914777-b57ef0c1-f7ae-4ed6-be87-c82cc357873d.png" width="50%" /> | <img src="https://user-images.githubusercontent.com/38860388/223914788-b170f60a-0a88-4f53-991e-3e86728d5b59.png" width="50%" /> |

🐛: 質問詳細画面_ニックネームが長い場合、コメントの経過時間が画面に収まるように修正

---

example-app/SantokuApp/package.json
example-app/SantokuApp/src/apps/app/__snapshots__/App.test.tsx.snap
example-app/SantokuApp/src/features/qa-home/pages/HomePage.tsx
example-app/SantokuApp/src/features/qa-home/pages/__snapshots__/HomePage.test.tsx.snap
example-app/SantokuApp/src/features/qa-question/components/QuestionListCard.tsx
example-app/SantokuApp/src/features/qa-question/components/QuestionListHeader.tsx

| 修正前 (Pixel 6/Android 13) | 修正後 (Pixel 6/Android 13) |
| <img src="https://user-images.githubusercontent.com/38860388/224254740-32ee2797-cfc3-49e9-817a-1828c2630bb7.png" width="50%" /> | <img src="https://user-images.githubusercontent.com/38860388/224254790-20847dec-d46a-4963-aa97-d1c75a60b4a3.png" width="50%" /> |
| 修正前 (Pixel 6/Android 13) | 修正後 (Pixel 6/Android 13) |
| <img src="https://user-images.githubusercontent.com/38860388/224254839-18af5785-622d-4e76-b418-11f18e1bc1e6.png" width="50%" /> | <img src="https://user-images.githubusercontent.com/38860388/224255060-a0c9e35a-1cd5-4cf0-a845-6bd997ffff68.png" width="50%" /> |

🐛: home画面_スクロール時に質問ラベル行が固定表示されるように修正

---

example-app/SantokuApp/src/bases/ui/theme/restyleTheme.ts
example-app/SantokuApp/src/features/qa-question/pages/QuestionDetailPage.tsx

| 修正前 (Pixel 6/Android 13) | 修正後 (Pixel 6/Android 13)  |
| <img src="https://user-images.githubusercontent.com/38860388/224961603-86c16456-3ad3-4d1b-aed6-6928795efa93.png" width="50%" /> | <img src="https://user-images.githubusercontent.com/38860388/224961808-55c4cb84-64f6-4f9b-a8a6-d1a6fe9f17c5.png" width="50%" /> |

🐛: 質問詳細画面_最下部スクロール時にコメントアイコンを押下できない不具合を改善

---

website/docs/react-native/learn/getting-started/create-project.md
website/docs/react-native/learn/getting-started/launch-created-app.mdx
website/docs/react-native/learn/qa-app/app-project-desc.md

📝: Update learn doc

---

example-app/SantokuApp/src/apps/app/navigators/AuthenticatedStackNav.tsx
example-app/SantokuApp/src/bases/ui/illustration/GoBackIllustration.tsx
example-app/SantokuApp/src/bases/ui/theme/restyleTheme.ts

| 修正前 (iPhone 12/iOS 16.2) | 修正後 (iPhone 12/iOS 16.2)  |
| <img src="https://user-images.githubusercontent.com/38860388/224966678-51c0e137-ca5d-4fa4-b179-cce5cd8045f2.png" width="50%" /> | <img src="https://user-images.githubusercontent.com/38860388/227157346-b9ab41c2-1736-4af1-a8f2-18860b32cda3.png" width="50%" /> |
修正前後でスタイルが変わっていない
| 修正前 (Pixel 6/Android 13) | 修正後 (Pixel 6/Android 13)  |
| <img src="https://user-images.githubusercontent.com/38860388/224965760-a5a56216-2ab4-4957-974e-e29fbb90900d.png" width="50%" /> | <img src="https://user-images.githubusercontent.com/38860388/224965814-b63a88d4-1cb1-4467-9076-f9e1130f972b.png" width="50%" /> |

🐛: 質問詳細画面_戻るボタンがデザインと異なる不具合を改善

---

example-app/SantokuApp/src/fixtures/msw/handlers/account/deleteAccountsMeAnswerCommentLikes.ts
example-app/SantokuApp/src/fixtures/msw/handlers/account/deleteAccountsMeAnswerLikes.ts
example-app/SantokuApp/src/fixtures/msw/handlers/account/deleteAccountsMeEventLikes.ts
example-app/SantokuApp/src/fixtures/msw/handlers/account/putAccountsMeAnswerCommentLikes.ts
example-app/SantokuApp/src/fixtures/msw/handlers/account/putAccountsMeAnswerLikes.ts
example-app/SantokuApp/src/fixtures/msw/handlers/account/putAccountsMeEventLikes.ts

🐛: 不具合_いいね更新時の条件誤りを修正

---

.github/workflows/gh-pages.yaml
website/.gitattributes
website/README.md

---
- `git diff` を `--binary` オプションありで実行しても lfs ファイルは `version https://git-lfs.github.com/spec/v1` から始まるtext差分を出します。これを apply patchできる形にするには `git lfs uninstall` が手軽です
- `actions/checkout` のドキュメント [actions/checkout: Action for checking out a repo](https://github.com/actions/checkout#usage)
>     # Whether to download Git-LFS files  
>     # Default: false  
>     lfs: ''

🧑‍💻: Git LFS 有効化(pptx)

---

example-app/SantokuApp/src/apps/app/navigators/AuthenticatedStackNav.tsx

- iOS13〜15環境のNative Stackのmodalは、端末の向き変更に画面が追従しない事象
- 回避方法
---
なし

💡: iOS13〜15環境のNative Stackのmodalは、端末の向き変更に画面が追従しない事象をコメントとして追記

---

website/docs/react-native/santoku/application-architecture/http-api/http-api-error-handling.mdx
website/docs/react-native/santoku/requirements/non-functional/usability.mdx

- リンク先がなくなっており、リンク先がなくても困らない記事内容のため、リンクを削除しました
- [Specifications](https://developer.apple.com/design/human-interface-guidelines/foundations/typography#specifications)よりも[Typography](https://developer.apple.com/design/human-interface-guidelines/foundations/typography)のほうが記事としてわかりやすいため、そちらをリンク先として設定しました
なし

📝: リンク先不正への対応

---

website/src/css/custom.css

- https://github.com/ws-4020/mobile-app-crib-notes/pull/332 の追加対応
- [Docsaurusの修正](https://github.com/facebook/docusaurus/pull/7129/files#diff-5548122e1da708235c90f8d8cc552ffa69c199f1dd82ca505c9577ac7255da73) で上記対応が効かなくなったみたいです
---
- 確認1-[REST APIの準備](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/todo-app/networking/setting-up-local-server/): <img width="846" alt="image" src="https://user-images.githubusercontent.com/1201990/230854022-4165d900-e902-45b3-9f66-8e1de5241df6.png">
- 確認2-[APIクライアントの作成](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/todo-app/networking/generate-api-client/): <img width="844" alt="image" src="https://user-images.githubusercontent.com/1201990/230854261-6816c73e-5b3e-47d0-ba15-c8b4692f3e50.png">
なし

💄: Improved Tab UI

---

website/src/plugins/medium-zoom-docusaurus-plugin/attach-medium-zoom.js

- https://github.com/gabrielcsapo/docusaurus-plugin-image-zoom
- https://github.com/facebook/docusaurus/pull/6732
- Not a public distributed plugin, so it does not support backward compatibility.
---
| before clicking image | after clicking image |
|--|--|
|<img width="812" alt="image" src="https://user-images.githubusercontent.com/1201990/231079387-f6b164cf-22a7-4d60-ae9e-e451cb5f2e50.png">|<img width="633" alt="image" src="https://user-images.githubusercontent.com/1201990/231079443-ede06c11-b0cb-4315-bac9-e2d748fafdf0.png">|
NaN

🐛: Fixed a bug that caused two image zooms to be displayed

---

website/docs/react-native/learn/getting-started/create-project.md

---
- https://github.com/ws-4020/rn-spoiler/pull/132

📝 rn-spoilerがExpo SDK 47にアップグレードしたので、学習コンテンツのプロキシに関する注意事項を削除

---

.github/workflows/app.yaml
.github/workflows/gh-pages.yaml

- GITHUB_WORKFLOW 環境変数を prefix につける
---
`GITHUB_WORKFLOW` 環境変数は `name` を参照する
- [Variables - GitHub Docs](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)
- `git grep -h -E "^(    )?name" .github/`
```
name: SantokuApp
name: (${{ github.workflow }}) Lints, Tests
name: DeleteDeployGateDistributionPages
name: Delete DeployGate distribution pages
name: Deploy
name: Deploy Pages
name: GitHub Pages
name: (${{ github.workflow }}) Lints
name: (${{ github.workflow }}) Build
name: Report
name: Report
name: Triage
```
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1105
merge されるまでは 冗長な表示になるみたい

🧑‍💻: GitHub Action の check 名が website と SantokuApp どちらのものか分かりづらい問題に対処

---

website/docs/react-native/santoku/development/build-configuration/development-account-for-ios.mdx

- plugin名のOS追加漏れに対応 (withAddPersonalAccountConfig)
* 関連PR
* https://github.com/ws-4020/mobile-app-crib-notes/pull/1028
* https://github.com/ws-4020/mobile-app-crib-notes/pull/1072
* 他に `withAddPersonalAccountConfig` は残ってない
```
$ git grep withAddPersonalAccountConfig | wc
0       0       0
```
```
$ git grep withAddPersonalAccountConfig origin/master 
origin/master:website/docs/react-native/santoku/development/build-configuration/development-account-for-ios.mdx:Expoが標準で用意しているConfig Pluginsには、開発者アカウントを設定するための機能がありません。そのため、このアプリでは[withAddPersonalAccountConfig](./apply-plugins#アプリで独自に作成したconfig-plugins)というプラグインを作成しています。
```

📝: withAddPersonalAccountConfig -> withIosAddPersonalAccountConfig

---

.azure-pipelines/deploy-all.yaml
.azure-pipelines/deploy-stg.yaml
.azure-pipelines/deploy.yaml
.tool-versions

---
- `git grep -F "3.1.3" -- ":!**/package-lock.json" ":!**/santoku-app-backend/**" ":!*.svg" ":!*.png" .`を実行して該当箇所がないことを確認

⬆️: Upgrade Ruby to 3.1.4とCIのトリガー変更

---

.github/pull_request_template.md

- Azure Pipeline の起動コマンドの説明にビルドバリアントが含まれているが、もう使用していないので削除
- `example-app/SantokuApp/.script/jobs/build-and-run-all-variants-macos.js` の更新
---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1024
```
$ git grep SantokuAppDebug
example-app/SantokuApp/.script/jobs/build-and-run-all-variants-macos.js:  'bundleDevSantokuAppDebug',
example-app/SantokuApp/.script/jobs/build-and-run-all-variants-macos.js:  'bundleDevSantokuAppDebugAdvanced',
example-app/SantokuApp/.script/jobs/build-and-run-all-variants-macos.js:  'bundleSantokuAppDebug',
example-app/SantokuApp/.script/jobs/build-and-run-all-variants-macos.js:  'bundleSantokuAppDebugAdvanced',
example-app/SantokuApp/.script/jobs/build-and-run-all-variants-macos.js:  ['devSantokuAppDebug', 'dev.debug'], …
```

📝: GitHub PR template から古いビルドバリアントについての記述を削除

---

example-app/SantokuApp/jest.config.js
example-app/SantokuApp/jest/__mocks__/@notifee/react-native.ts
example-app/SantokuApp/jest/__mocks__/@react-native-firebase/crashlytics.ts
example-app/SantokuApp/jest/__mocks__/@react-native-firebase/messaging.ts
example-app/SantokuApp/jest/__mocks__/@react-navigation/native.ts
example-app/SantokuApp/jest/__mocks__/expo-splash-screen.ts
example-app/SantokuApp/src/bases/logging/Logger.test.ts
example-app/SantokuApp/src/features/account/services/auth/autoLogin.test.tsx
example-app/SantokuApp/src/features/account/services/auth/canAutoLogin.test.ts
example-app/SantokuApp/src/features/account/services/auth/changeAccount.test.tsx
example-app/SantokuApp/src/features/account/services/auth/logout.test.tsx

Expo SDK 48アップグレードの対応で、`App.test.tsx`を実行すると以下のエラーが発生
> Error: Hooks cannot be defined inside tests. Hook of type "beforeEach" is nested within
`jest/__mocks__`配下のモックファイルは、モックしているライブラリなどが`import`、`require`されたときに読み込まれます。
テスト対象のコンポーネントの内部で、条件によって`require`するライブラリを切り替えている箇所があり、それが原因でこのエラーが発生したと思われます。
そのため、`jest/__mocks__`配下のモックファイルでモックをクリアするのをやめて、`jest.config.js`の[clearMocks](https://jestjs.io/ja/docs/configuration#clearmocks-boolean)を有効化する方法で、テスト実施前にモックをクリアします。
- 対象は以下で確認
---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1118
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1118#discussion_r1175939353

🩹: Jestでテスト実施前のモッククリア方法を修正

---

website/package-lock.json
website/package.json

Docusaurus関連のパッケージは固定ではなくバージョン範囲指定（パッチ範囲）に変更。
パッチバージョンは一般的にBreaking Changesはなく不具合対応が反映されるため、固定にしないほうが良いと判断。
また、`redocusaurus`はバージョン範囲がマイナーになっていましたが、マイナーには機能追加が含まれる場合があり、Lockfile maintenanceで対応するスコープの対象外にしたいため、バージョン範囲をパッチに変更
対象パッケージは以下
---
なし

📌: Docusaurus関連のパッケージバージョン範囲をパッチに変更

---

.github/renovate.json5

📌: Exclude development tools from renovate

---

.github/renovate.json5

`redocusaurus`の依存パッケージには`@docusaurus/xxx`が含まれており、Docusaurus関連のパッケージと同時にvupしないと、正常にビルドができない場合があります。
そのため、Docusaurus関連のパッケージとまとめてvupするように変更します。
---
なし

📌: redocusaurusはDocusaurus関連のパッケージとまとめてvupするように変更

---

example-app/santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/system/nablarch/AccountInitializer.java
example-app/santoku-app-backend/src/main/resources/env.config
example-app/santoku-app-backend/src/main/resources/rest-component-configuration.xml

モバイルのログイン画面から、MSWとバックエンド双方のログインを透過的に実施するため、MSWの初期アカウントと同じアカウントをバックエンドにも作成します。
バックエンドに初期データとして登録するアカウントは以下の3つです。
- santoku
- admin
- partner
パスワードは、環境設定ファイル、または環境変数から設定可能です。
なし

✨: バックエンドに初期データとしてMSWと同じアカウントを登録

---

example-app/SantokuApp/src/fixtures/msw/handlers/system/getSystemCsrfToken.ts

CSRFトークンの取得APIのレスポンスで、以下を返却するように修正
---
以下のコマンドをこのプルリクエストのコメントとして投稿すると、
- https://github.com/nablarch/nablarch-fw-web/blob/1.9.0/src/main/java/nablarch/common/web/WebConfig.java#L27-L30

🐛: MSWで、CSRFトークンの取得APIのレスポンスに誤りがあったので修正

---

example-app/SantokuApp/src/features/account/services/account/useAccountCommands.ts
example-app/SantokuApp/src/features/qa-home/services/useRequestPermissionAndRegisterToken.ts

---
以下のコマンドをこのプルリクエストのコメントとして投稿すると、
なし

🐛: デバイストークン登録後にアカウントデータがリフレッシュされていなかった事象の対応

---

example-app/SantokuApp/.script/managed-license.js

🔧: managed-licenseの更新

---

example-app/SantokuApp/src/apps/app/App.test.tsx

`App.tsx`のテスト実行時に日付を固定していないため、テストが落ちていました。
例えば、以下のデータが取得できなくなり、スナップショットが変更されてしまってテストエラーになっていました。
- https://github.com/ws-4020/mobile-app-crib-notes/blob/v2023.03/example-app/SantokuApp/src/fixtures/msw/datas/eventData.ts#L95
そのため、現在のスナップショットに変更が入らない日付で固定します。
---
なし

✅: App.tsxのテスト実行時に、日付を固定する

---

website/docs/react-native/santoku/development/build-configuration.mdx
website/docs/react-native/santoku/development/build-configuration/about-plugins.mdx
website/docs/react-native/santoku/maintenance/enhance/expo-46-upgrade.mdx
website/docs/reference/security/awesome-sites.md

- [英語版のサイト](https://mobile-security.gitbook.io/masvs/) は`v1.3.1`までしか更新されておらず、それと同じバージョンを参照するには、Github側を参照するしかないため
- ↑のリンク修正と合わせて、ドキュメント上で参照しているリンク先は古いことを、セキュリティリンクページの先頭で警告表示
---
なし

🩹: ドキュメントのリンク切れ対応

---

website/src/pages/trademark.md

- Meta
- Google
- Mapbox
※ 元々含まれていたが商標リストから漏れていたものを含む
---
- [商標について | Fintan](https://fintan.jp/page/1622/)
- [商標 | Meta | Brand Resource Center](https://about.meta.com/ja/brand/resources/meta/our-trademarks/)
- [Brand Resource Center | Trademark list](https://about.google/brand-resource-center/trademark-list/)
- [MAPBOX Trademark of MAPBOX, INC. - Registration Number 3962620 - Serial Number 77836269 :: Justia Trademarks](https://trademarks.justia.com/778/36/mapbox-77836269.html)
- [商標について | Fintan » Mobile App Development](https://ws-4020.github.io/mobile-app-crib-notes/trademark/)
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1139
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1054
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1166

📝: 商標追加: React, React Native, Firestore, fastlane, Google Maps, Mapbox

---

website/.eslintrc.js
website/docusaurus.config.js
website/src/plugins/fix-footnote-order-plugin/fix-footnote-order.js
website/src/plugins/fix-footnote-order-plugin/index.js

- 脚注の順番が不正な問題に対応するpluginを追加
---
- `/mobile-app-crib-notes/react-native/santoku/decisions/adr-004-deep-link/#fnref-2`
1. ページ表示更新時 (`onRouteDidUpdate`) に2〜を実行
- 参考：[Client architecture | Docusaurus](https://docusaurus.io/docs/advanced/client#client-module-lifecycles)
1. 脚注 `.footnotes ol li` を配列にして id `fn-([0-9]+)` を元に、番号順にソート
2. 順番に `appendChild`
- 無駄に append することもあるが簡略化のため。
※ hashが変わっただけで  `onRouteDidUpdate` が呼ばれるので、効率化のため、HTMLが変わってなくて2回目実行はSKIPするように data 属性でチェック
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1199
- 現状確認：[ディープリンクの実現方式 | Fintan » Mobile App Development](https://ws-4020.github.io/mobile-app-crib-notes/react-native/santoku/decisions/adr-004-deep-link/#fnref-2)
- 2と3が入れ替わっている
- 根本対応には Docusaurus 3 が必要
- [Footnotes in tables rendered out of order · Issue #6625 · …

📝: 脚注の順番が不正な問題に対応するpluginを追加

---

example-app/SantokuApp/jest.config.js

jestのcoverage測定対象から以下を除外。
カバレッジ測定の度に手動で `coveragePathIgnorePatterns` を追加するのは手間なのでリポジトリに含める。
- 自動生成コード
- 画面
- src/features/backend/apis
- src/features/sandbox/apis
- src/apps/app/screens/
- src/features/*/pages/
※ デモ機能, QAアプリに限らない
---
- `53.87% Statements 2519/4676` → `62.66% Statements 2132/3402`
- 元々は自動生成コードのみを除外する予定だったのでブランチ名が不正確となっている
- 現時点で除外対象のテストコードはとても少ない（全111テストファイル中）
- 自動生成コード: 0ファイル
- 画面: 3ファイル
- src/features/account/pages/LoginPage.test.tsx
- src/features/account/pages/ProfileRegistrationPage.test.tsx
- src/features/qa-home/pages/HomePage.test.tsx
- eslint の `ignorePatterns` には以下が記載されていたが、 API定義以外はテスト対象ではなかった（レポートに存在しなかった）ので、`coveragePathIgnorePatterns` には追加していない。
```
ignorePatterns: [
'src/features/backend/apis/**/*.ts',
'src/features/sandbox/apis/**/*.ts', …
```

🧑‍💻: jestのcoverage測定対象から自動生成コード・画面を除外

---

.github/renovate.json5

expoによる管理対象であるため以下をrenovate対象外に指定
- react-native-maps
- expo-status-bar
- androidx.swiperefreshlayout:swiperefreshlayout
- prebuildで生成される部分
- jest-expo
- @expo/config-plugins
---
過去に`.github/renovate.json5`から消したが、含まれているのが自然＆大きな問題も無いと思われるため戻す
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1118/commits/e0d01763d42ae8102c05d7b15528c34d6da49ff0
- https://github.com/ws-4020/rn-spoiler/pull/133#discussion_r1188040581
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1165#pullrequestreview-1478494515
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1186#pullrequestreview-1534045748
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1167#pullrequestreview-1534024230
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1189#pullrequestreview-1534187696
- …

🧑‍💻: renovate対象外を追加

---

example-app/SantokuApp/.eslintrc.js
example-app/SantokuApp/src/bases/core/errors/ApplicationError.test.ts
example-app/SantokuApp/src/bases/core/errors/RuntimeError.test.ts
example-app/SantokuApp/src/bases/local-authentication/LocalAuthentication.test.ts
example-app/SantokuApp/src/bases/message/Message.test.ts
example-app/SantokuApp/src/bases/ui/picker/DateTimePicker.ios.test.tsx
example-app/SantokuApp/src/features/backend/utils/customInstance.ts

以下の課題を解決するため、[@typescript-eslint/ban-ts-comment](https://typescript-eslint.io/rules/ban-ts-comment/)を追加しました。
- `@ts-ignore`は、ignoreする必要がない場合に検知できない
- エラーをignoreする場合は、必ず理由を記載したい
なし

✨ @ts-directiveに関するルールを追加

---

example-app/SantokuApp/.eslintrc.js

- チェック内容が重複したため（`no-restricted-syntax`はObjectの`for-in`文もチェックしてくれるので、そっちを採用）
---
以下のコードでLintエラーになることを確認
```typescript
const a = ['a', 'b', 'c'];
for (const v in a) { } // ESLint: for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.(no-restricted-syntax)
const b = {a: '1'};
for (const v in b) { } // ESLint: for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.(no-restricted-syntax)
```
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1201
- https://eslint.org/docs/latest/rules/no-restricted-syntax
- https://github.com/airbnb/javascript/blob/master/packages/eslin …

✨: for-in文を禁止するESLintルールを追加

---

example-app/SantokuApp/app.config.js
example-app/SantokuApp/config/plugin/src/android/withAndroidAddAppActivityAndroidManifest.ts
example-app/SantokuApp/patches/@expo+config-plugins+6.0.2.patch
example-app/SantokuApp/patches/README.md
example-app/SantokuApp/prebuild/local/android/app/src/main/AndroidManifest.xml

原因: `withAndroidAddAppActivityAndroidManifest.ts`で`MainActivity`の`intent-filter`に固定値を設定していたため
- https://github.com/ws-4020/rn-spoiler/blob/v2023.06.0/template/patches/%40expo%2Bconfig-plugins%2B6.0.1.patch#L102
---
- `npm run prebuild`を実行して差分がないことを確認
- `app.config.js`に`intentFilters`を設定後、`AndroidManifest.xml`に指定した値が反映されることを確認
`app.config.js`に`intentFilters`を設定
```
intentFilters: [
{
autoVerify: true,
action: 'VIEW',
data: [
{
scheme: 'https',
host: 'example.com',
},
],
category: ['BROWSABLE', 'DEFAULT'],
},
],
```
`AndroidManifest.xml`のdiff
```diff
<action android:name="android.intent.action.MAIN"/>
<category android:name="android.intent.category.LAUNCHER"/>
</intent-filter>
+      <intent-filter android:autoVerify="true" data-generated="true">
+        <action …
```

🐛: app.config.jsに設定したintentFilterがAndroidManifest.xmlに反映されない問題の対応

---

example-app/SantokuApp/tsconfig.json

- [module]( https://www.typescriptlang.org/tsconfig#module)
- `target`を`esnext`に指定している場合（SantokuAppの設定の場合）は、デフォルトで`es6/es2015`が指定されます
- 元々`commonjs`が指定されていましたが、React NativeでもExpoでも`es6/es2015`が使われているので問題ない認識です。
- https://github.com/facebook/react-native/blob/main/packages/typescript-config/tsconfig.json#L6
- https://github.com/expo/expo/blob/sdk-48/packages/expo/tsconfig.base.json
- [allowSyntheticDefaultImports](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports)
- [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop)が`true`の場合は`allowSyntheticDefaultImports`もデフォルトでtrueになるので、コメントアウトしても特に影響はありません
---
以下のコマンドをこのプルリクエストのコメントとして投稿すると、
- /azp run deploy-stg
- /azp run deploy-dev …

🔧: tsconfigに設定している一部項目をexpo-template-blank-typescriptの設定に合わせる

---

website/docs/react-native/santoku/decisions/linking-feasibility.mdx
website/docs/react-native/santoku/decisions/non-linking-feasibility.mdx

`Linking.openURL`を実行して`Linking.addEventListener`を呼び出すような記載をしている箇所がありましたが、iOSの場合は`Linking.openURL`を実行するとブラウザが開いてしまうため、それに関する記載を見直しました。
---
なし

📝 ディープリンクの画面遷移に関するADRでLinking.openURLを使用している箇所を修正

---

example-app/SantokuApp/jest/__mocks__/expo-linking.ts

`expo-linking`の`addEventListener`から返却される`subscription`が`undefined`のためエラーログが出力されている模様（テストは成功してる）
```
console.error
Warning: Internal React error: Attempted to capture a commit phase error inside a detached tree. This indicates a bug in React. Likely causes include deleting the same fiber more than once, committing an already-finished tree, or an inconsistent return pointer.
Error message:
TypeError: Cannot read properties of undefined (reading 'remove')
```
- とりあえず、SantokuAppで使用している関数でNativeにアクセスしているものをmock化しています
---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1213

🤡: App.test.tsxの自動テスト実行時にエラーログが出力されていたので対応

---

example-app/SantokuApp/prebuild/dev/android/app/src/debug/AndroidManifest.xml
example-app/SantokuApp/prebuild/local/android/app/src/debug/AndroidManifest.xml
example-app/SantokuApp/prebuild/prod/android/app/src/debug/AndroidManifest.xml
example-app/SantokuApp/prebuild/stg/android/app/src/debug/AndroidManifest.xml

- ref: expo/expo@93b8858485243e1bd310ca6a79187b0b8973e235 `[templates][android] update template to replace usesCleartextTraffic`
---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1221

📸: expo-template-bare-minimumが更新されたのでPrebuildを実施

---

.github/renovate.json5

expoによる管理対象であるため`expo-dev-client`をrenovate対象外に指定
---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1207
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1219#discussion_r1320909027

🧑‍💻: renovate対象外を追加（expo-dev-client）

---

website/docs/react-native/learn/qa-app/app-project-desc.md

- `expo-keep-awake`の`activateKeepAwake` → `activateKeepAwakeAsync`
- activateKeepAwakeはdeprecatedでありwarningがでるため
---
- `git grep --word-regexp activateKeepAwake` で [Expo48記事](https://ws-4020.github.io/mobile-app-crib-notes/react-native/santoku/maintenance/enhance/expo-48-upgrade#expo-keep-awake)しかhitしないことを確認
- `cd website` && `npm start`
- http://localhost:3000/mobile-app-crib-notes/react-native/learn/qa-app/app-project-desc の `src/apps/app/use-cases/useAppInitializer.ts` ファイルを新規プロジェクトに追加
- `activateKeepAwakeAsync` 行の警告が消えることを確認
そもそも、`activateKeepAwakeAsync`は`DEV`の場合expoが呼んでいそうなので不要かもしれないが、それは別で対応する。
- [expo/packages/expo/src/launch/registerRootComponent.tsx at 1f98cdd7a0a365e1e2b2569ae813fa1a2d9409f1 · expo/expo](https://github.com/expo/expo/blob/1f98cdd7a0a365e1e2b2569ae813fa1a2d9409f1/p …

📝: activateKeepAwake -> activateKeepAwakeAsync

---

website/docs/react-native/learn/basic-concepts/react-navigation-basics/param.mdx

- 型エラーを現状と揃える
- エラーの発生場所を明示
理由：紛らわしいため
---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/202
- 「応用編」追加
- https://github.com/ws-4020/mobile-app-crib-notes/pull/503
- `React Navigation` v5 -> v6
- https://github.com/ws-4020/mobile-app-crib-notes/pull/609
- 「概要」の `型チェックを実質的に無効化して利用しています ` 追加
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1255#discussion_r1357810721

📝: react-navigation: 型エラーの説明を改善

---

website/docusaurus.config.js

- rnSpoilerTagをmasterからv2023.9.0に変更（固定）
- masterのままだとrn-spoilerにmergeしたものが即座に使用されてしまい、ドキュメントと不整合になるため
---
- ※ `--npm`無しのyarnを使った場合、post-installが動きません。元（`patch-package`が入ったとき）から。
- https://github.com/ws-4020/rn-spoiler/pull/71
- > RN Spoilerのバージョニングは、セマンティックバージョニングに従う必要はありません。ただ、Yarnがインストールされた環境でreact-native initするとデフォルトではYarnが選択されてしまい、エラーになってしまう
- :memo: ↑は2023/10に `npx react-native -v: 9.3.2`, `yarn: 1.22.19`, `rn-spoiler tag: v2023.09.0` で試したところ問題なかった。おそらく、タグ名ではなく、package.jsonのversionのことと思われる。
- https://github.com/ws-4020/mobile-app-crib-notes/pull/367
- https://github.com/ws-4020/mobile-app-crib-notes/pull/967
- タグ一覧: [Tags · ws-4020/rn-spoiler](https://github.com/ws-4020/rn-spoiler/tags)
- `v2023.09.0`形式(月が0始まり)のやつは間違えたものですが、リンク切れ回避のため残してあるものです
- 今後のタグは0無しの`v2023.9.0`形式で。
- :memo: …

📝: rnSpoilerTagを更新

---

website/docs/react-native/learn/qa-app/app-project-desc.md

- npx pod-install → npm run pod-install
- 過去に変更していたものの漏れに対応
---
rn-spoilerには `pod-install` scriptが定義済み
```
"pod-install": "cd ios && bundle exec pod install --repo-update",
```
https://github.com/ws-4020/rn-spoiler/blob/v2023.6.0/template/package.json#L18
- https://github.com/ws-4020/mobile-app-crib-notes/pull/967
- https://github.com/ws-4020/mobile-app-crib-notes/pull/967/commits/10df043894cc1d489c30d73674deef6e4d84b830 `change pod install from npx to npm scripts`

📝: pod-install方法をnpm runに統一

---

website/docs/react-native/learn/qa-app/app-project-desc.md

- 不要なスペースを削除(prettier警告対策)
- no-throw-literal warn 修正
---
[Q&Aアプリプロジェクトの説明 | Fintan » Mobile App Development](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/qa-app/app-project-desc#qa%E3%82%A2%E3%83%97%E3%83%AA%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E8%A8%AD%E5%AE%9A)
- `src/apps/app/use-cases/useAppInitializer.ts`
- `src/apps/app/AppWithInitialization.tsx`
- https://github.com/ws-4020/mobile-app-crib-notes/pull/883
- https://github.com/ws-4020/mobile-app-crib-notes/pull/956
- https://github.com/ws-4020/mobile-app-crib-notes/commit/9d7235a6835075804559d80d4189c046678895a0 ``fix @typescript-eslint/no-throw-literal warning``
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1269 …

📝 : Q&Aアプリ初期設定のWarn修正

---

website/docs/distribution/app-build/ios-build-setting.md

- 開発用プロビジョニングプロファイルのType表現を修正
- :x: Apple Development
- :o: Development
※ Apple Developmentは証明書のType
---
[iOSプロジェクトのビルド設定 | Fintan » Mobile App Development](https://fintan-contents.github.io/mobile-app-crib-notes/distribution/app-build/ios-build-setting/#configuration%E3%81%AE%E8%A8%AD%E5%AE%9A)
> 開発用プロビジョニングプロファイル（Apple Development）を指定
- https://developer.apple.com/account/resources/certificates/add
- > Apple Development
- https://developer.apple.com/account/resources/profiles/add

📝: 開発用プロビジョニングプロファイルのType表現修正

---

website/docs/react-native/learn/getting-started/create-project.md
website/docusaurus.config.js

- プロジェクトの作成ページにVisual Studio Code用の推奨設定について追記
---
- `.vscode/` は`v2023.9.0`タグには存在しなく`master`ブランチに存在するため
- すでに以下PRでmasterブランチに入っていますが、関係性のわかりやすさ・rnSpoilerTagの更新についての周知のためにcommitに含めています（mergeするときに差分は消えます）
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1269
- [プロジェクトの作成 | Fintan » Mobile App Development](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/getting-started/create-project)
- https://github.com/ws-4020/rn-spoiler/pull/151

📝: 学習コンテンツのプロジェクトの作成ページにVisual Studio Code用の推奨設定について追記

---

website/docs/react-native/learn/todo-app/screens/welcome.mdx

- 修正したコードに対する説明文章を追記 
- 「アプリの実装前に」に設定していたリンク先は`initialRouteName`の説明をしているセクションに変更
---
学習コンテンツを一通り確認しましたが、以前の学習コンテンツに丸投げ感のある表現はWelcomeページだけでした。

🩹: 学習コンテンツで、コードに対する説明文章が適切ではない箇所があったので修正

---

website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx

- 他のコード欄にもTypeエラーを修正する必要があります。
- [typescript-docs-verifier](https://github.com/bbc/typescript-docs-verifier)ライブラリを使用して確認した内容は以下のなります。
- 下記のスクリプトを追加し、コマンドを実行すると「importエラー」などを誤検知しています。
```
"scripts": {
"verifier-doc": "find docs -type f -name '*.mdx' -o -name '*.md' | xargs typescript-docs-verifier --input-files"
}
```
- 下記のようにコード欄にタイトルがあるとエラーの場合でも検知できない状態です。 
https://github.com/ws-4020/mobile-app-crib-notes/blob/31b075ea63a6eaaaba22399351e35cd1dc0c1861/website/docs/react-native/santoku/application-architecture/error-handling/how-to-handle-error.mdx#L100
なし

📝: ドキュメントのコード欄にTypeエラーを修正

---

example-app/SantokuApp/src/features/account/services/account/useAccountCommands.ts

🐛: isLoading設定誤りを修正

---

README.md

[extensible-custom-error](https://github.com/necojackarc/extensible-custom-error)を利用させていただいているファイルが違っていたので修正
なし

🩹: MIT Licenseで提供されているソースコード（extensible-custom-error）の利用箇所リンクが間違っているので修正

---

website/docs/react-native/santoku/application-architecture/http-api/http-api-tanstack-query.mdx
website/docs/react-native/santoku/development/implement/style-guide/eslint.mdx
website/docs/react-native/santoku/maintenance/enhance/expo-49-upgrade.mdx

- 過去アップグレード記事からのExpo SDKドキュメントへのリンク先修正
- リダイレクトはされていて参照先ページは確認できること、アップグレード時点の記事として内容は正しいことから修正せず
---
なし

📝: リンク切れを修正

---

website/docusaurus.config.js

📌: ドキュメントから参照するrn-spoilerのタグを更新

---

website/docs/react-native/learn/getting-started/create-project.md

- 理由: v0.76.0以降だと失敗するようになったため
- 恒久対応(2024/12/31までに必要)
---
```
$ git grep 'react-native init' v2024.10
v2024.10:website/docs/react-native/learn/getting-started/create-project.md:npx react-native init --npm --template https://github.com/ws-4020/rn-spoiler#{@inject: rnSpoilerTag} <YourAppName>
v2024.10:website/docs/react-native/learn/getting-started/create-project.md:npx react-native init --template https://github.com/ws-4020/rn-spoiler#{@inject: rnSpoilerTag} <YourAppName>
v2024.10:website/docs/react-native/learn/getting-started/create-project.md:初めて`npx react-native init ...`を実行すると、次のように不足しているパッケージをインストールするかと聞かれます。`react-native`をインストールしようとしていれば問題ないので、エンターキーを押して実行してください。
$ git grep 'react-native init' | wc --lines
0
```
```
$ npx react-native init --npm --template …
```

📝: fix: npx react-native init が失敗する問題に暫定対処

---

.github/workflows/gh-pages.yaml

- @actions/upload-artifactで指定していたバージョン3が非推奨になりCIがエラーになったためバージョン4にアップデート
---
- masterブランチにmerge後にGitHub Pagesを更新するCIが動く予定だが、それが失敗するので、[（動作確認用）GitHub Pages](https://ws-4020.github.io/mobile-app-crib-notes/)が更新されない
- https://github.com/ws-4020/mobile-app-crib-notes/actions/runs/15414208587/job/43373043392#step:1:43
- > `Error: Missing download info for actions/upload-artifact@v3`
- v4では隠しファイルが除外されるようになったため
- → コスパを考慮して、PRのmerge後のCIで動作確認する（ws-4020側はGitHub Pagesが壊れても問題ないため）
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1334#pullrequestreview-2891582311
* [actions/upload-artifact](https://github.com/actions/upload-artifact?tab=readme-ov-file#actionsupload-artifact)
* > actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024. [Learn …

chore: gh-pages用actions/upload-artifactをv4に更新
