santoku-app/.env
santoku-app/.gitignore
santoku-app/android/app/build.gradle
santoku-app/android/app/src/main/java/jp/fintan/mobile/santokuapp/generated/BasePackageList.java
santoku-app/ios/Podfile.lock
santoku-app/ios/SantokuApp.xcodeproj/project.pbxproj
santoku-app/package-lock.json
santoku-app/package.json
santoku-app/src/app/AppConfig.ts

Manage secret values without local diffs
[AB#5152](https://dev.azure.com/ws-4020/d7a19fb0-b312-4b39-8b66-3fc0f61016f5/_workitems/edit/5152)

🔨: Change how to manage secretes

---

santoku-app/src/app/components/basics/KeyboardAvoidingView.tsx
santoku-app/src/app/components/basics/index.ts
santoku-app/src/app/components/parts/StatefulLoginForm.tsx

None
[AB#5148](https://dev.azure.com/ws-4020/d7a19fb0-b312-4b39-8b66-3fc0f61016f5/_workitems/edit/5148)

✨: Add component for keyboard avoiding

---

santoku-app/ios/SantokuApp.xcodeproj/project.pbxproj
santoku-app/ios/SantokuApp.xcodeproj/xcshareddata/xcschemes/SantokuApp AppStore.xcscheme
santoku-app/ios/SantokuApp/Info.plist

None
None
[AB#5149](https://dev.azure.com/ws-4020/d7a19fb0-b312-4b39-8b66-3fc0f61016f5/_workitems/edit/5149)

🔨: Add configuration for App Store

---

santoku-app/ios/SantokuApp.xcodeproj/project.pbxproj

I incremented project version for ios from 3 to 4.

📝: Increment project version for iOS

---

santoku-app/android/app/build.gradle
santoku-app/android/app/src/main/AndroidManifest.xml
santoku-app/android/gradle.properties

* Remove unused permissions
* Bump version code
* Fix version name

🎉: Prepare internal test for Android

---

src/css/custom.css

---
自分としては、結構いい感じにできたんじゃないかな？って。

🌱: Change admonition styles

---

.github/workflows/gh-pages.yml

🔨: Change directory to publish to GitHub Pages

---

docusaurus.config.js

---
`ws-4020`のリポジトリの方はドラフトなので、`noIndex`を設定するようにしました。

🔨: Change organization name according to repo name

---

src/components/PageList.module.css
src/components/PageList.tsx
src/components/index.ts

---
ヘッダをリンクにするだけだと少し物足りなかったのでコンポーネントを作成してみました。

🌱: Add PageList component

---

.idea/dictionaries/ryotan.xml
src/pages/index.tsx
src/pages/styles.module.css

💄: Use PageList component in the landing page

---

docs/react-native/learn/getting-started.md
docs/react-native/learn/getting-started.mdx

💄: Use PageList component in the getting-started overview page

---

docs/react-native/troubleshooting/unable-to-load-script.mdx

表記が壊れていた部分などを修正

---

docs/react-native/troubleshooting/cant-build-in-xcode.md
docs/sidebars.js

XCodeでビルドが失敗する。

---

docs/react-native/learn/todo-app/app-project-desc.md
docs/sidebars.js

- RNスポイラで作成される各ファイルやディレクトリの説明
「RNスポイラで作成される各ファイルやディレクトリの説明」については、React Native固有でないものも多く冗長と感じたので説明を省きました。

🖋️: ToDoアプリプロジェクトの説明

---

santoku-app-backend/.gitignore
santoku-app-backend/.vscode/extensions.json
santoku-app-backend/.vscode/launch.json
santoku-app-backend/.vscode/settings.json
santoku-app-backend/.vscode/tasks.json
santoku-app-backend/README.md
santoku-app-backend/host.json
santoku-app-backend/openapi.yaml
santoku-app-backend/pom.xml
santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/backend/Firebase.java
santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/backend/api/NotifyToDevice.java
santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/backend/api/PublishToTopic.java
santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/backend/api/SubscribeToTopic.java
santoku-app-backend/src/main/java/jp/fintan/mobile/santokuapp/backend/api/UnsubscribeFromTopic.java

🌱: プッシュ通知用のバックエンドAPIの実装

---

santoku-app/.env
santoku-app/src/app/AppConfig.ts
santoku-app/src/app/backend/notification/PushNotificationService.ts
santoku-app/src/app/components/pages/notification/PushNotification.tsx
santoku-app/src/app/components/parts/notification/DeviseTokenNotificationForm.tsx
santoku-app/src/app/components/parts/notification/TopicNotificationForm.tsx

- Android Emulator以外での確認
- native baseの挙動不備？の修正
- API_TOKEN、API_URIを `.env` に指定
---
なし

🌱: BackendのAPIの呼び出し

---

docs/react-native/learn/getting-started/setting-up-development-environment.mdx

トラブルシュートに導線はった

---

docs/react-native/learn/getting-started/create-project.md

RN-Spoilerのハンズオン用タグ指定

---

santoku-app/index.js
santoku-app/ios/Podfile
santoku-app/ios/Podfile.lock
santoku-app/src/app/backend/notification/PushNotificationService.ts
santoku-app/src/app/components/pages/notification/PushNotification.tsx
santoku-app/src/app/components/parts/notification/FormInput.tsx
santoku-app/src/app/components/parts/notification/TopicNotificationForm.tsx

- バッジを設定する
- AndroidEmulator以外の動作確認
---
なし

通知メッセージを表示するようにする

---

docs/react-native/learn/getting-started/create-project.md

🐛: リンク切れの修正

---

santoku-app/ios/SantokuApp.xcodeproj/project.pbxproj

🔧: Xcodeのビルド設定を更新（npx pod install）

---

.idea/dictionaries/ryotan.xml
santoku-app-backend/README.md

🚨: Fix textlint errors

---

santoku-app/src/app/components/pages/notification/PushNotification.tsx
santoku-app/src/app/components/parts/notification/DeviceTokenNotificationForm.tsx
santoku-app/src/app/components/parts/notification/TopicNotificationForm.tsx

---
Androidビルドができないので動作確認できてない

🐛 deviceのtypoを修正

---

santoku-app/src/app/components/pages/notification/PushNotification.tsx

ドキュメントの実装に合わせる

---

docs/sidebars.js
docusaurus.config.js
src/pages/index.tsx
src/pages/styles.module.css

🖋: 不要なガイドページの削除（リンク含む）

---

docs/react-native/learn/getting-started.mdx
docs/reference/auth/overview.md
docs/reference/notification/overview.md

サイドバーのタイトルを概要からOverviewに変更し、Overviewのタイトルは全体のタイトルへ

---

src/pages/trademark.md

🖋: 商標登録のやつ書いた

---

.github/workflows/triage.yaml

🐛: github actionsのtriageが失敗する問題に対応する

---

.github/workflows/app.yaml
.github/workflows/gh-pages.yaml

- on.pull_request -> on.pull_request_targetに修正
- PullRequestでGitHubActionsがFintan−Contentsで動作する
---
なし

🌱: GitHub Actionsはpull request targetにするように修正

---

docusaurus.config.js

---
- ローカルでの確認ができてないので [master](https://ws-4020.github.io/mobile-app-crib-notes/)で検証したい

🐛 link切れのためredirect

---

docs/react-native/troubleshooting/unable-to-load-script.mdx

🖋️: コマンド例が正しくないので修正

---

docs/react-native/learn/getting-started/setting-up-development-environment.mdx

🖋️: proxy設定のコマンド誤りを修正

---

SantokuApp/src/navigation/RootStackNav.tsx
SantokuApp/src/screens/home/Home.tsx
SantokuApp/src/screens/index.ts
SantokuApp/src/screens/info/ApplicationInfo.tsx
SantokuApp/src/screens/info/index.ts

- アプリケーション名
- アプリケーションID / Bundle Identifier
- バージョン
- ビルド番号
- `__DEV__`
---
なし

🌱: Add a page to view application information

---

docs/react-native/learn/basic-concepts/react-native-basics/components/lists/flat-list.mdx

🖋: FlatListのサンプルでWarningが出ないように修正

---

santoku-app/README.md
santoku-app/android/app/google-services.dummy.json

---
google-services.dummy.jsonになっているので、google-services.jsonにしてから起動する必要があります

🌱: google-services.jsonのダミーファイル追加

---

docs/distribution/build/android-build.md

🖋: Androidのビルドの説明を公式に寄せる

---

.tool-versions
SantokuApp/Gemfile
SantokuApp/Gemfile.lock
SantokuApp/package.json

🔧: Add packages to Gemfile for Ruby 3.0

---

README.md

🖋: npm installではなくnpm ciを使って欲しい

---

docs/react-native/learn/todo-app/auth.mdx

🐛: TODOアプリハンズオンの誤字を修正

---

docs/react-native/learn/todo-app/networking/api-request.mdx

🖋: REST API呼び出しのcurlコマンドを修正

---

docs/react-native/learn/todo-app/screens/welcome.mdx

以下で対応手段について検討。
Discussions  https://github.com/ws-4020/mobile-app-crib-notes/discussions/250

🖋: 画面の実装前にApp.tsxを元に戻す記載を追加

---

docs/react-native/learn/todo-app/screens/todo-form.mdx

---
https://github.com/ws-4020/mobile-app-crib-notes/issues/284

🐛: 不要な`を削除

---

docs/react-native/learn/todo-app/networking/api-request.mdx

---
https://github.com/ws-4020/mobile-app-crib-notes/issues/289

🐛: 書き換え方のガイド方法が間違っているので修正

---

docs/react-native/learn/todo-app/screens/auth.mdx

🖋: App.tsxの場所を修正。/src/contexts/App.tsx -> /src/App.tsx

---

docs/react-native/learn/todo-app/screens/login.mdx

🖋: ログイン画面で張り付けるLogin.tsxのprettierエラーを修正

---

docs/react-native/learn/getting-started.mdx

🖋: Getting StartedのOverviewの「環境構築」を左ペインにあわせて「開発環境の構築」に修正

---

docs/react-native/learn/basic-concepts/react-native-basics.md

🖋: 流用してそうな説明があるのでコアコンポーネントへのリンクを追加

---

docs/react-native/learn/getting-started/create-project.md

🖋: 記載方法を変えてexpoへのリンク切れを回避する

---

docusaurus.config.js

---
もともとはリンク名は「Mobile App Top」と話してましたが、「Home」の方がかっこいいなと思ったので「Home」にしてあります。

💄: ナビゲーションバーにトップページへのリンクを作成

---

docs/react-native/learn/todo-app/screens/auth.mdx

🖋: Promiseのno voidエラーに対して注意書きコメントを追加＋prettier警告対応

---

docs/react-native/learn/todo-app/screens/auth.mdx
docs/react-native/learn/todo-app/screens/modal.mdx
docs/react-native/learn/todo-app/screens/tab.mdx
docs/react-native/learn/todo-app/screens/todo-board.mdx

---
ハンズオン完了後のnpm run lint実行結果（3ファイル、計4箇所）
```
todo_app_0617\src\navigation\AuthedStackNav.tsx
6:1 warning navigation/MainTabNav import should occur before import of react import/order
todo_app_0617\src\navigation\UnauthedStackNav.tsx
18:43 warning Insert , prettier/prettier
19:9 warning Delete ⏎···· prettier/prettier
todo_app_0617\src\screens\todo\TodoBoard.tsx
97:42 warning Insert ; prettier/prettier
```

🎨: 全通しテストで発見したprettierの警告を修正

---

docs/react-native/learn/todo-app/screens/auth.mdx
docs/react-native/learn/todo-app/screens/stack.mdx

🎨: lint警告を修正

---

src/css/custom.css

💄: TabのUI改善

---

docs/react-native/learn/advance/react-navigation-param.mdx
docs/react-native/learn/basic-concepts/react-navigation-basics.mdx
docs/react-native/learn/basic-concepts/react-navigation-basics/tab.mdx
docs/react-native/learn/todo-app/networking/activity-indicator.mdx

🎨: ソースコード例内の「省略」の表記ゆれを修正

---

docs/react-native/learn/getting-started/supplement.md

🐛: Tabs, TabItemのインポート漏れを修正

---

docusaurus.config.js

---
GitHub Pagesでも確認できるようにしたいです。

✨: ドキュメントのDraft版でExample Appを表示するように変更

---

.gitignore
.idea/codeStyles/Project.xml
.idea/dictionaries/shared.xml
.idea/encodings.xml
.idea/jsLibraryMappings.xml
.idea/jsLinters/eslint.xml
.idea/misc.xml
.idea/prettier.xml
.idea/vcs.xml
.tool-versions

---
ちょっとローカルに差分が出るようになってしまったので、このタイミングで更新しておきたいです。

🔨: Bump tool versions, update IntelliJ IDEA settings

---

website/docs/docusaurus/plugins.md
website/docusaurus.config.js

---
RN Spoiler側で、プロジェクト作成のコマンドはテスト済です。
https://github.com/ws-4020/rn-spoiler/pull/71

🐛: チュートリアルでプロジェクトの作成に使うRN Spoilerのバージョン名を変更

---

website/docs/react-native/santoku/decisions/adr-001-error-handling.mdx

🐛: エラーハンドリングのADRのステータスをAcceptedに変更

---

website/docs/react-native/santoku.mdx

- ADR用のOverviewやTopページの作成
---
他にいい方法があれば提案してほしいです。

🐛  ADRのリンクがDevelopmentにとんでいるので修正してみました

---

website/docs/react-native/santoku/development/build-configuration/build-variants.mdx

🩹: 例として記載しているアプリケーションIDが、誤解しやすいものだったので修正

---

.idea/codeStyles/Project.xml

---
IntelliJ IDEA 2021.2.1での設定

🔨: IntelliJ IDEAの設定ファイルを最新化

---

.github/workflows/gh-pages.yaml
website/.htmltest.yaml
website/docs/react-native/santoku/application-architecture/deep-link/process-deep-link.mdx
website/docs/reference/auth/login-screens.md

🩹: htmltestでリンクをチェックする要素を見直し、リンク切れを修正

---

website/src/css/custom.css

---
今までは、カーソルの変化に奇跡的に気づかない限りは、リンクがあるなんて気づけなかったw
変更後（リンクの表示スタイル）
変更前（リンクの表示スタイル）
変更後（全体）
変更前（全体）

💄: Noteなどのスタイルを修正

---

website/docs/react-native/santoku/application-architecture/error-handling/overview.mdx
website/docs/react-native/santoku/decisions.mdx
website/docs/react-native/santoku/decisions/adr-001-error-handling.mdx

---
ADRの議論の内容が、グローバルエラーハンドリングに関する内容のため、タイトルを変更しました

✨: ADRのエラーハンドリングのタイトルをグローバルエラーハンドリングに変更

---

.github/renovate.json5

✨: Flipperをrenovate対象外にする

---

.github/workflows/gh-pages.yaml

🔨: Fintan-contentsへのPull Requestではhtmltestをスキップするように修正

---

website/.htmltest.yaml
website/docusaurus.config.js

---
何かあれば記載してください。
なければ「なし」と記載してください。

🩹: ヘッダリンクにExample Appを表示するように修正

---

website/docs/react-native/learn/basic-concepts/pre-requisites.md

---
ひとまず、おそらく同じような内容と思われるページにリンクしました。

🩹: サバイバルTypeScriptへのリンクを修正

---

website/docs/react-native/santoku/requirements/non-functional/operation.mdx
website/docs/react-native/santoku/requirements/non-functional/overview.mdx
website/docs/sidebars.js

- 全体の体裁を既存ドキュメントレベルへの見直し
---
ESLintのエラーの解消で操作していたところブランチがマージできない状態になってしまったため再度PR作成しました。

📝: サンプルアプリの非機能要件「運用に関する事項」を追加

---

website/docs/react-native/santoku/decisions/adr-006-logging.mdx

https://github.com/ws-4020/mobile-app-crib-notes/discussions/574 の対応

✨: ログ出力のADR内の誤字を修正

---

.github/renovate.json5

📌: santoku-app-backendをRenovateの対象から除外

---

example-app/SantokuApp/jest/__mocks__/react-native-screens.js
example-app/SantokuApp/src/components/button/Button.test.tsx
example-app/SantokuApp/src/components/button/__snapshots__/Button.test.tsx.snap
example-app/SantokuApp/src/components/snackbar/FullWindowOverlay.test.tsx
example-app/SantokuApp/src/components/snackbar/FullWindowOverlay.tsx
example-app/SantokuApp/src/components/snackbar/Snackbar.test.tsx
example-app/SantokuApp/src/components/snackbar/Snackbar.tsx
example-app/SantokuApp/src/components/snackbar/WithSnackbar.test.tsx
example-app/SantokuApp/src/components/snackbar/__snapshots__/FullWindowOverlay.test.tsx.snap
example-app/SantokuApp/src/components/snackbar/__snapshots__/Snackbar.test.tsx.snap
example-app/SantokuApp/src/components/snackbar/__snapshots__/WithSnackbar.test.tsx.snap
example-app/SantokuApp/src/components/webview/WebView.test.tsx
example-app/SantokuApp/src/components/webview/__snapshots__/WebView.test.tsx.snap

- Snackbarの表示中のSnackbar表示関数実行による、割り込みの条件分岐網羅
- AnimatedのアニメーションはfakeTimerで細かく制御できないため、手動で確認する
なし

✅: 共通コンポーネントのテスト

---

website/docs/reference/auth/manage-credentials.md

🩹: typo SharedPreference -> SharedPreferences

---

website/docs/react-native/santoku/development/development-environment/00.setting-up-environment.mdx

🖋: Update SantokuApp development environment setting up instruction

---

website/docs/react-native/learn/todo-app/networking/activity-indicator-each-todo.mdx
website/docs/react-native/learn/todo-app/networking/activity-indicator.mdx
website/docs/react-native/learn/todo-app/screens/todo-board.mdx
website/docs/react-native/learn/todo-app/screens/todo-form.mdx
website/docs/react-native/learn/todo-app/screens/use-focus-effect.mdx

💄: Fix lint errors in the learning content

---

example-app/santoku-app-backend/README.md

- ローカル環境での接続手順は追加していません
- `FIREBASE_SERVICE_ACCOUNT` という環境変数に秘密鍵（json）を設定すれば動くかと思うが未検証
- 開発ガイドに書く内容なのか迷ったので一旦READMEに記載
- 開発ガイドへ書くのであれば、こちらは削除してもいいかもです

📝: FCMへの接続手順を追加

---

example-app/SantokuApp/src/__snapshots__/App.test.tsx.snap
example-app/SantokuApp/src/components/webview/WebView.tsx
example-app/SantokuApp/src/components/webview/__snapshots__/WebView.test.tsx.snap
example-app/SantokuApp/src/screens/account/__snapshots__/TermsOfServiceAgreementScreen.test.tsx.snap

💄: iOSでWebViewのデフォルトスクロール減速が速すぎたので、少し遅くなるように変更

---

example-app/SantokuApp/src/screens/demo/authentication/useAuthentication.tsx

🩹: 認証デモ内の不要なHooksのdependenciesを削除

---

example-app/SantokuApp/src/framework/utilities/id.test.ts
example-app/SantokuApp/src/framework/utilities/id.ts

🩹: ランダム値の偏りをなくすように修正

---

website/docs/react-native/santoku/application-architecture/auth/credential-management.mdx
website/docs/react-native/santoku/application-architecture/logging-app/logging.mdx
website/docs/react-native/santoku/application-architecture/logging-app/overview.mdx
website/docs/react-native/santoku/design/screen-specs/basic-policy.mdx

🩹: Githubページで発生する404対応

---

website/src/pages/trademark.md

📝: 認証方式の文章内に登場する商標の追記

---

example-app/SantokuApp/src/framework/authentication/AuthenticationService.test.ts
example-app/SantokuApp/src/framework/authentication/AuthenticationService.ts
example-app/SantokuApp/src/framework/authentication/SecureStorageAdapter.test.ts
example-app/SantokuApp/src/framework/authentication/SecureStorageAdapter.ts
example-app/SantokuApp/src/screens/demo/authentication/AuthenticationScreen.tsx
example-app/SantokuApp/src/screens/demo/authentication/useAuthentication.tsx

- ログアウト時にパスワード（ログイン資格情報）も削除するよう修正
なし

♻️: 出荷審査の指摘対応でデモ画面を修正

---

website/landing-page/react-native-example-app-architecture-description.md

2月公開分の更新履歴をランディングページに反映

---

website/docusaurus.config.js

📈: Disable analytics

---

website/docs/react-native/learn/basic-concepts/react-native-basics/components.mdx

🩹: NativeBaseへのリンクが切れていたので修正

---

website/docs/react-native/santoku/development/implement.mdx
website/docs/react-native/santoku/development/implement/http-api.mdx
website/docs/sidebars.js

📝: HTTP APIの開発ガイド作成

---

website/landing-page/react-native-example-app-architecture-description.md

📝: 3月Fintan公開LP作成

---

website/docs/react-native/santoku/application-architecture/http-api/http-api-react-query.mdx

📝: デフォルト値の列を追加

---

example-app/SantokuApp/src/screens/demo/react-query/ListTodoDemoScreen.tsx
example-app/SantokuApp/src/screens/demo/react-query/useCreateTodoDemo.ts
example-app/SantokuApp/src/screens/demo/react-query/useListTodoDemo.ts

🩹: 第三者レビュー指摘対応

---

example-app/SantokuApp/.eslintignore
example-app/SantokuApp/.eslintrc.js

🩹: Refine ESLint config

---

.idea/misc.xml

🔨: Change JavaScript language level to Flow (IntelliJ IDEA)

---

example-app/SantokuApp/package-lock.json
example-app/SantokuApp/package.json

➕: FormikとYupを追加

---

example-app/SantokuApp/src/components/picker/YearMonthPicker.android.test.tsx
example-app/SantokuApp/src/components/picker/YearMonthPicker.ios.test.tsx

🚑: YearMonthPickerのテストが失敗していたので修正

---

example-app/SantokuApp/src/components/overlay/snackbar/Snackbar.test.tsx

🚑: M1環境だとSnackbarのテストが失敗していたので修正

---

example-app/SantokuApp/ios/Podfile.lock
example-app/SantokuApp/package-lock.json
example-app/SantokuApp/package.json
example-app/SantokuApp/src/components/picker/DateTimePicker.android.test.tsx
example-app/SantokuApp/src/components/picker/DateTimePicker.android.tsx
example-app/SantokuApp/src/components/picker/DateTimePicker.ios.test.tsx
example-app/SantokuApp/src/components/picker/DateTimePicker.ios.tsx
example-app/SantokuApp/src/components/picker/DateTimePicker.tsx
example-app/SantokuApp/src/components/picker/DateTimePickerItems.tsx
example-app/SantokuApp/src/components/picker/__snapshots__/DateTimePicker.android.test.tsx.snap
example-app/SantokuApp/src/components/picker/__snapshots__/DateTimePicker.ios.test.tsx.snap
example-app/SantokuApp/src/components/picker/useDateTimePickerAndroidUseCase.ts
example-app/SantokuApp/src/components/picker/useDateTimePickerIOSUseCase.ts
example-app/SantokuApp/src/components/picker/useDateTimePickerUseCase.ts
example-app/SantokuApp/src/screens/demo/picker/PickerScreen.tsx
example-app/SantokuApp/src/screens/demo/picker/usePickerScreenUseCase.ts

✨: DateTimePickerを追加

---

example-app/SantokuApp/src/framework/authentication/AuthenticationService.test.tsx

🚨: Fixed lint error

---

example-app/SantokuApp/src/framework/backend/refreshSession.ts
example-app/SantokuApp/src/generated/BundledMessages.ts

🔊: Send log on session refresh error

---

example-app/SantokuApp/src/App.tsx
example-app/SantokuApp/src/components/overlay/OverlayContainer.test.tsx
example-app/SantokuApp/src/components/overlay/OverlayContainer.tsx
example-app/SantokuApp/src/components/overlay/__snapshots__/OverlayContainer.test.tsx.snap
example-app/SantokuApp/src/screens/terms/__snapshots__/TermsAgreementOverlay.test.tsx.snap

💄: Centering terms overlay

---

website/docs/react-native/learn/getting-started/setting-up-development-environment.mdx

📝: 学習コンテンツの開発環境の構築の記述内容の見直し

---

example-app/SantokuApp/src/features/account/services/auth/autoLogin.test.tsx
example-app/SantokuApp/src/features/account/services/auth/changeAccount.test.tsx

🚨: Fix unused import

---

example-app/SantokuApp/package-lock.json
example-app/SantokuApp/package.json
example-app/SantokuApp/src/bases/ui/common/StyledSvgIconBase.tsx
example-app/SantokuApp/src/bases/ui/common/index.tsx
example-app/SantokuApp/src/bases/ui/fab/Fab.tsx
example-app/SantokuApp/src/bases/ui/illustration/PersonIllustration.tsx
example-app/SantokuApp/src/bases/ui/theme/AppThemeProvider.tsx
example-app/SantokuApp/src/bases/ui/theme/restyleTheme.ts
example-app/SantokuApp/src/bases/ui/theme/theme.ts

💄: Add bases ui for qa app

---

example-app/SantokuApp/ios/Podfile.lock

---
Leakage of updating Podfile.lock when react-native-svg is installed.

⬆️: Update Podfile.lock

---

example-app/SantokuApp/src/fixtures/msw/handlers/system/getSystemAppUpdatesTypeVersion.ts

🐛: Fix required update mock message

---

example-app/SantokuApp/ios/SantokuApp.xcodeproj/project.pbxproj

✨: Support iPad

---

website/docs/react-native/santoku.mdx

📝: Refactoring Documentation - Introduction

---

example-app/SantokuApp/src/bases/ui/common/StyledColumn.tsx
example-app/SantokuApp/src/bases/ui/common/StyledRow.tsx
example-app/SantokuApp/src/bases/ui/common/StyledSpace.tsx
example-app/SantokuApp/src/bases/ui/common/getSpacedChildren.tsx
example-app/SantokuApp/src/bases/ui/common/types.ts
example-app/SantokuApp/src/features/qa-question/components/AddCommentButton.tsx
example-app/SantokuApp/src/features/qa-question/components/AnswerDetailCard.tsx
example-app/SantokuApp/src/features/qa-question/components/CommentCard.tsx
example-app/SantokuApp/src/features/qa-question/components/CommentsButtonWithCount.tsx
example-app/SantokuApp/src/features/qa-question/components/CommentsLikeButtonWithCount.tsx
example-app/SantokuApp/src/features/qa-question/components/DiffDaysOrHours.tsx
example-app/SantokuApp/src/features/qa-question/components/QuestionAndAnswerLikeButtonWithCount.tsx
example-app/SantokuApp/src/features/qa-question/components/QuestionDetailCard.tsx
example-app/SantokuApp/src/features/qa-question/components/QuestionPost.tsx
example-app/SantokuApp/src/features/qa-question/components/TagsSheet.tsx
example-app/SantokuApp/src/features/qa-question/components/TemplateClearChip.tsx
example-app/SantokuApp/src/features/qa-question/components/ViewsButtonWithCount.tsx
example-app/SantokuApp/src/features/qa-question/pages/QuestionDetailPage.tsx

💄: Add component that can specify gap and space

---

website/docs/react-native/santoku/test-planning/ut-planning.mdx

📝: refactor document ut-planning

---

example-app/SantokuApp/src/apps/app/__snapshots__/App.test.tsx.snap
example-app/SantokuApp/src/bases/ui/common/StyledFlatList.tsx
example-app/SantokuApp/src/features/qa-home/pages/HomePage.tsx
example-app/SantokuApp/src/features/qa-home/pages/__snapshots__/HomePage.test.tsx.snap

---
ref:
- https://fettblog.eu/typescript-react-generic-forward-refs/
- https://github.com/Shopify/restyle/issues/166

✨: Add StyledFlatList

---

website/docs/react-native/learn/todo-app/screens/auth.mdx

Draft because it depend on rn-spoiler expo sdk 46 upgrade
---
none

📝: Support Expo SDK 46 for todo app learning

---

.github/renovate.json5

📌: Exclude @testing-library/react-native from renovate management

---

example-app/SantokuApp/src/fixtures/msw/handlers/question/postAnswerComments.ts

🐛: Fix postAnswerComment in msw data

---

website/docs/react-native/santoku/design/screen-specs/screens/splash-screen/overview.mdx

📝: fix splash screen

---

website/docs/react-native/santoku.mdx

📝: fix santoku app agenda

---

website/docs/react-native/santoku/design/screen-specs/screens/terms-of-service-agreement/overview.mdx

📝: Removed the link in the snackbar

---

website/docusaurus.config.js

📈: Add a script of Plausible Analytics to website

---

example-app/SantokuApp/src/features/qa-home/pages/HomePage.tsx

🐛: Fix problem with scroll top fab not working

---

example-app/SantokuApp/README.md

📝: ws-4020 -> fintan-contents

---

.tool-versions

⬆️: Bump ruby to v3.1.3

---

example-app/SantokuApp/src/apps/app/__snapshots__/App.test.tsx.snap
example-app/SantokuApp/src/features/qa-question/components/QuestionListCard.tsx

| 修正前 (Pixel 6/Android 13) | 修正後 (Pixel 6/Android 13) |
| <img src="https://user-images.githubusercontent.com/38860388/224189282-a4270b00-16fe-4a77-a317-84702330ca11.png" width="50%" /> | <img src="https://user-images.githubusercontent.com/38860388/224189294-dd6737ee-c97d-44f4-97ab-21fdbefebede.png" width="50%" /> |

🐛: home画面_解決済みの質問に解決済みラベルが付くように修正

---

website/landing-page/react-native-example-app-architecture-description.md

📝: update landing page

---

website/docusaurus.config.js

📈: Fix the target domain name of Plausible

---

website/src/pages/trademark.md

- iPad
- Dynamic Island
- ESLint
- AQUOS
---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1081
- 全体テスト計画(※ 現時点ではファイル未更新)

📝: 商標追加「iPad」「Dynamic Island」「ESLint」「AQUOS」

---

website/landing-page/react-native-example-app-architecture-description.md

landing page 更新時の漏れに対応
- Config Plugin対応 -> Config Plugins対応
- テストエンジニア -> QA専門ベンダー
---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1087
- Config Plugins対応: https://github.com/ws-4020/mobile-app-crib-notes/pull/1087#discussion_r1148683045
- QA専門ベンダー: https://github.com/ws-4020/mobile-app-crib-notes/pull/1087#discussion_r1148739978

📝: Fix landing page/react native example app architecture description

---

website/.htmltest.yaml
website/docs/react-native/learn/qa-app/app-project-desc.md
website/docs/react-native/learn/todo-app/networking/setting-up-local-server.mdx

📝: ドキュメントの軽微な修正

---

website/docs/react-native/learn/qa-app/app-project-desc.md
website/docs/react-native/santoku/development/dependency-management.md

📝: パッケージ追加に関するドキュメントの軽微な修正

---

example-app/SantokuApp/src/bases/ui/modal/ModalBackdrop.tsx

| 修正前 (iPhone 12/iOS 16.2) | 修正後 (iPhone 12/iOS 16.2)  |
| <img src="https://user-images.githubusercontent.com/38860388/229044899-7ad8c497-2ed4-4ac5-8b84-f0246bcbed95.png" width="50%" /> | <img src="https://user-images.githubusercontent.com/38860388/229038190-52370802-5c14-4000-9bcc-66e1fea34cd8.png" width="50%" /> |
| 修正前 (iPhone 12/iOS 16.2) | 修正後 (iPhone 12/iOS 16.2)  |
| <img src="https://user-images.githubusercontent.com/38860388/229044931-f642206d-325a-4ac0-91a3-21da02bae225.png" width="50%" /> | <img src="https://user-images.githubusercontent.com/38860388/229038227-3afac838-52b5-4365-b3fb-aaa7826e0489.png" width="50%" /> |
| 修正前 (iPhone 12/iOS 16.2) …

🐛: modalのlandscape対応

---

example-app/SantokuApp/patches/README.md

- `example-app/SantokuApp/patches/README.md` の `##` に `[${package名}]` を追加
---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1118#discussion_r1174715406

📝: パッチ用READMEの各変更にpackage名prefixを追加して対象がわかりやすくする

---

example-app/SantokuApp/config/plugin/src/android/withAndroidAddManifestPlaceholders.ts

---
`app.config.js`に以下を設定して`prebuild`
```javascript
[
withAndroidAddManifestPlaceholders,
[
{placeholderKey: 'test', propertyKey: 'propKey'}, // デフォルト値なしで、`gradle.properties`から取得するテスト
{placeholderKey: 'test2', propertyKey: 'propKey2', propertyDefaultValue: 'defaultValue'}, // デフォルト値ありで、`gradle.properties`から取得するテスト
],
],
```
`build.gradle`の`defaultConfig`に以下が追加されていることを確認
```
manifestPlaceholders.test = findProperty('propKey')
manifestPlaceholders.test2 = findProperty('propKey2') ?: 'defaultValue'
```
`gradle.properties`に以下を追加
```
propKey=1234567890
```
`AndroidManifest.xml`に以下を追加してして`npm run android`
```
<application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" …
```

✨: manifestPlaceholdersを設定するConfigPluginの改善

---

website/landing-page/react-native-example-app-architecture-description.md

📝: 2023/06 Fintan公開用にLPを更新

---

example-app/SantokuApp/src/apps/app/App.test.tsx

🚨: 不要にlintをdisableしていた箇所を修正

---

website/docs/react-native/learn/getting-started/setting-up-development-environment.mdx

- Windows用PATH設定例を追加
---
|プレビュー|
|:----|
| <img src="https://github.com/ws-4020/mobile-app-crib-notes/assets/13145001/defdd680-adf7-4c34-84db-c945df09ec24"> |
対象ページ
[開発環境の構築 | Fintan » Mobile App Development](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/getting-started/setting-up-development-environment)

📝: Windows用PATH設定例を追加

---

example-app/SantokuApp/.eslintrc.js
example-app/SantokuApp/src/bases/core/contexts/createUseContextAndProvider.ts
example-app/SantokuApp/src/bases/core/utils/composePressableStyles.ts
example-app/SantokuApp/src/bases/validator/loginPasswordValidator.ts
example-app/SantokuApp/src/features/demo-react-query/pages/ListTodoDemoPage.tsx

現在Nablarchの[JavaScriptコーディング規約](https://github.com/Fintan-contents/nablarch-system-development-guide/blob/master/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E9%96%8B%E7%99%BA%E3%82%AC%E3%82%A4%E3%83%89/PGUT%E5%B7%A5%E7%A8%8B/proman-style-guide/js/JavaScript%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84.docx)を参考に規約を作成していますが、それには以下の規約があります。
> 2.1.9 制御構文中の括弧の省略 ★
言語仕様上、省略が許されている括弧についても、必ず明示的に記述する。
次のコードはif文の括弧を省略している。
これは、ESLintのルールで制御できそうなので、`curly`をルールに追加しました。
なし

✨ ESLintのルールにcurlyを追加

---

website/docs/react-native/santoku/development/implement/style-guide/eslint.mdx

---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1201
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1205

📝: 適用しているESLintルール一覧を最新化

---

example-app/SantokuApp/.script/print-eslint-rules.js

---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1226

🔨 ESLintルールを表示するツールの改善

---

website/docs/react-native/santoku/decisions.mdx

修正対象は次のように確認（URLの一部に利用されている`/decisions/`は問題ないので除外）
```
❯❯❯ git grep -i decisions | grep -v '/decisions/'
website/docs/react-native/santoku.mdx:    to: '/react-native/santoku/decisions',
website/docs/react-native/santoku/decisions.mdx:title: Decisions Records
website/docs/react-native/santoku/decisions.mdx:pagination_label: Decisions Records - 目次
website/docs/sidebars.js:        'react-native/santoku/decisions',
website/landing-page/react-native-example-app-architecture-description.md:また、アプリ開発現場でこのサンプルアプリケーションをより有効に活用してもらうため、方式設計などについては検討過程も「[Decision Records](https://ws-4020.github.io/mobile-app-crib-notes/react-native/santoku/decisions)」として公開しています。
```
以下の該当箇所は、URLとして利用しているだけなので修正不要
* `website/docs/react-native/santoku.mdx:    to: '/react-native/santoku/decisions',`
* …

✏️: "Decisions Records" -> "Decision Records"

---

example-app/SantokuApp/src/features/acknowledgements/services/useAssetContent.ts

---
| 修正前 (Pixel XL/Android 13) | 修正後 (Pixel XL/Android 13)  |
| <img src="https://github.com/ws-4020/mobile-app-crib-notes/assets/146910578/0ec3541d-b6f8-4d21-b7d6-4055597b91c8" width="50%" /> | <img src="https://github.com/ws-4020/mobile-app-crib-notes/assets/146910578/23cb1835-4690-4341-8c8a-1af4ff892bf0" width="50%" /> |
| 修正前 (iPhone SE/iOS 16.2) | 修正後 (iPhone SE/iOS 16.2)  |
| <img src="https://github.com/ws-4020/mobile-app-crib-notes/assets/146910578/ea00fe4a-cef5-4680-9ff7-ce6f9409789d" width="50%" /> | <img src="https://github.com/ws-4020/mobile-app-crib-notes/assets/146910578/f7dbeae9-225f-4b0e-a41b-b481ea09cf5b" width="50%" /> |

🐛: ライセンス情報が表示されるように修正

---

website/docs/react-native/learn/todo-app/networking/generate-api-client.mdx

📝: OPEN APIコマンド修正に伴うドキュメント修正

---

example-app/SantokuApp/src/features/app-updates/services/useAppUpdates.ts
example-app/SantokuApp/src/features/demo-react-query/pages/DisableErrorHandlerDemoPage.tsx
example-app/SantokuApp/src/features/demo-react-query/services/item/useItem.ts
example-app/SantokuApp/src/features/demo-react-query/services/item/useItemInfo.ts

🐛: 命名規約に従って修正

---

website/docs/react-native/santoku/development/implement/style-guide/eslint.mdx

- 以下のコマンドの実行結果を反映
- `node .script/print-eslint-rules.js`
- `node .script/print-eslint-rules.js  src/apps/app/App.test.tsx`
---
なし

📝: ESLint関連のvupに伴うルール一覧の更新

---

website/docusaurus.config.js

📌: ドキュメントから参照するrn-spoilerのタグを更新

---

website/docs/react-native/learn/qa-app/app-project-desc.md

- `msw@v1`
- `@mswjs/data@v0.15` 
mswは2系がリリースされているが、現状のQ&Aアプリに提供しているコードは2系に対応していないため
---
- https://github.com/ws-4020/mobile-app-crib-notes/pull/1270

📌: Q&Aアプリで使用するmswのバージョンを指定

---

website/docs/react-native/santoku/maintenance/enhance/expo-50-upgrade.mdx

📝: @expo/vector-iconsの変更内容について記載を追加

---

website/docs/reference/auth/authn-architecture.md
website/docs/reference/security/awesome-sites.md

📝: OWASP MASに関する記載及びリンク先を修正

---

website/docs/react-native/santoku/maintenance/enhance/expo-50-upgrade.mdx
website/docs/react-native/santoku/maintenance/enhance/expo-51-upgrade.mdx

📝: Expoのアップグレード記事を修正

---

website/docs/react-native/learn/getting-started/create-project.md

- [プロジェクトの作成](https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/getting-started/create-project/)で`npx react-native init`コマンドの代わりに`npx @react-native-community/cli init`コマンドを使用
- 理由: 2024/12/31 で 動作が変わり動かなくなる予定のため
- npmではなくyarnを利用したい場合用の備考を削除
- 理由: --pm オプションだけでなく、他にも変更しないと動かない＆動作確認ができていないため
---
```
$ npx react-native@0.75.4 init --npm --template https://github.com/ws-4020/rn-spoiler#v2024.10.0 test1
⚠️ The `init` command is deprecated.
The behavior will be changed on 2024/12/31 (5 days).
- Switch to npx @react-native-community/cli init for the identical behavior.
- Refer to the documentation for information about alternative tools: https://reactnative.dev/docs/getting-started
Running: npx @react-native-community/cli init
Welcome to React Native!
Learn once, write anywhere …
```

📝: deprecatedな npx react-native コマンドを npx @react-native-community/cli に変更

---

.github/workflows/app.yaml

---
以下のコマンドをこのプルリクエストのコメントとして投稿すると、
- /azp run deploy-stg
- /azp run deploy-dev
- `stg`, `dev` の両方
何かあれば記載してください。
なければ「なし」と記載してください。

🩹: upload-artifact@v3をv4にアップデート
